// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: f7162968d3fd38877dafb70e9491ef4dd29cad60f83590984908c73c7ed9077f]
// 模型: UserEntity (TKWF.Ext.Identity.UserEntity)
// 生成时间: 2026-09-14 08:06:01
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.Identity;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>UserEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>UserEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class UserEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>精确匹配：UXIdentityUserNormalizedUserName（Unique 索引，必填参数）</summary>
        public static Expression<Func<UserEntity, bool>> ByUXIdentityUserNormalizedUserName(string normalizedUserName)
            => x => x.NormalizedUserName == normalizedUserName;

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<UserEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<UserEntity, bool>> All(params Expression<Func<UserEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<UserEntity, bool>> Any(params Expression<Func<UserEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>UserEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<UserEntity>
    {

        /// <summary>精确匹配：UXIdentityUserNormalizedUserName（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByUXIdentityUserNormalizedUserName(string normalizedUserName)
            => (PredicateBuilder)Update(Conditions.ByUXIdentityUserNormalizedUserName(normalizedUserName));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<UserEntity> CreateBranch() => new PredicateBuilder();
}
}
