// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: e13ea625569535bbb7a59072d425290ee6326f10a62542f7624a055fd6c45e05]
// 模型: NotificationEntity (TKWF.Ext.Notifications.NotificationEntity)
// 生成时间: 2026-09-12 00:30:07
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Notifications;

namespace TKWF.Ext.Notifications.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>NotificationEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>NotificationEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record NotificationEntityDto : IDomainDto<NotificationEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 通知名（稳定唯一，如 "OrderShipped"——与 RegistrationDefinition.Name 对应）。 </summary>
    public required string Name { get; init; }
    /// <summary> 显示名快照（发布时从定义复制，避免运行时查定义）。 </summary>
    public string? DisplayName { get; init; }
    /// <summary> 通知数据（键值对 JSON，<see cref="M:TKWF.Ext.Notifications.NotificationData.ToJson"/> 产出）。 </summary>
    public string? DataJson { get; init; }
    /// <summary> 严重级别（<see cref="T:TKWF.Ext.Notifications.NotificationSeverity"/> 枚举值）。 </summary>
    public int Severity { get; init; }
    /// <summary> 关联实体类型（可选，实体级通知——匹配订阅）。 </summary>
    public string? EntityTypeName { get; init; }
    /// <summary> 关联实体 ID（可选，实体级通知——匹配订阅）。 </summary>
    public string? EntityId { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static NotificationEntityDto FromEntity(NotificationEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new NotificationEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Name = entity.Name,
            DisplayName = entity.DisplayName,
            DataJson = entity.DataJson,
            Severity = entity.Severity,
            EntityTypeName = entity.EntityTypeName,
            EntityId = entity.EntityId,
            CreateTime = entity.CreateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<NotificationEntity, NotificationEntityDto>> SelectExpression => e => new NotificationEntityDto
    {
        Id = e.Id,
        Name = e.Name,
        DisplayName = e.DisplayName,
        DataJson = e.DataJson,
        Severity = e.Severity,
        EntityTypeName = e.EntityTypeName,
        EntityId = e.EntityId,
        CreateTime = e.CreateTime,
    };
    #endregion

    NotificationEntity IDomainDto<NotificationEntity>.ApplyToEntity(NotificationEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(DisplayName), d => d.DisplayName, (e, v) => e.DisplayName = v )
            .Map(nameof(DataJson), d => d.DataJson, (e, v) => e.DataJson = v )
            .Map(nameof(Severity), d => d.Severity, (e, v) => e.Severity = v )
            .Map(nameof(EntityTypeName), d => d.EntityTypeName, (e, v) => e.EntityTypeName = v )
            .Map(nameof(EntityId), d => d.EntityId, (e, v) => e.EntityId = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
        ;
        return entity;
    }

    NotificationEntity IDomainDto<NotificationEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(NotificationEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<NotificationEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<NotificationEntity, NotificationEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class NotificationEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static NotificationEntityDto ToDto(this NotificationEntity entity) => NotificationEntityDto.FromEntity(entity);
}

