// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 5856cb2d523515498f1602a33152536dd174ff3ac8cae11dbdae80fbeae0dc0b]
// 模型: NotificationPreferenceEntity (TKWF.Ext.Notifications.NotificationPreferenceEntity)
// 生成时间: 2026-09-14 08:06:02
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Notifications;

namespace TKWF.Ext.Notifications.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>NotificationPreferenceEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>NotificationPreferenceEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record NotificationPreferenceEntityDto : IDomainDto<NotificationPreferenceEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 偏好用户 ID。 </summary>
    public long UserId { get; init; }
    /// <summary> 偏好通知名（对齐 Notification.Name）。 </summary>
    public required string NotificationName { get; init; }
    /// <summary> 通道列表 JSON（如 ["Email"]；null = 回退定义级——P2-3 统一 JSON 存储）。 </summary>
    public string? ChannelsJson { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（UTC）。 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static NotificationPreferenceEntityDto FromEntity(NotificationPreferenceEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new NotificationPreferenceEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UserId = entity.UserId,
            NotificationName = entity.NotificationName,
            ChannelsJson = entity.ChannelsJson,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<NotificationPreferenceEntity, NotificationPreferenceEntityDto>> SelectExpression => e => new NotificationPreferenceEntityDto
    {
        Id = e.Id,
        UserId = e.UserId,
        NotificationName = e.NotificationName,
        ChannelsJson = e.ChannelsJson,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    NotificationPreferenceEntity IDomainDto<NotificationPreferenceEntity>.ApplyToEntity(NotificationPreferenceEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(NotificationName), d => d.NotificationName, (e, v) => e.NotificationName = v )
            .Map(nameof(ChannelsJson), d => d.ChannelsJson, (e, v) => e.ChannelsJson = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    NotificationPreferenceEntity IDomainDto<NotificationPreferenceEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(NotificationPreferenceEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<NotificationPreferenceEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<NotificationPreferenceEntity, NotificationPreferenceEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class NotificationPreferenceEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static NotificationPreferenceEntityDto ToDto(this NotificationPreferenceEntity entity) => NotificationPreferenceEntityDto.FromEntity(entity);
}

