// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: bd9ee8319b5a227164b721c23f3c7ea1a861e595f5091e23d25baccd48a77718]
// 模型: CalendarEntity (TKWF.Ext.Calendar.CalendarEntity)
// 生成时间: 2026-09-14 08:05:51
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Calendar;

namespace TKWF.Ext.Calendar.DTOs;
/// <summary>日历实体——多日历隔离（Code 唯一索引，F1）。     <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>；     保留 BCL <c>[Table("Calendar")]</c>（<c>FreeSqlTableStructureSynchronizer</c> 靠它发现实体建表）；     列映射用 FreeSql <c>[Column]</c>（IsPrimary/IsIdentity/Position，全限定避免与 BCL Schema 特性名冲突）。</para>     <para>删除语义：物理删除（硬删）——<b>不声明 IsDeleted</b>，DataService 基类 <c>hasSoftDelete:false</c>；     删除保护（无事件）由 Manager 层强制（D17）。</para>     <para>审计字段（D5）：<c>DateTime</c>（UTC）显式声明（对齐 DataDictionary/Tagging 先例，     FreeSql SQLite 不支持 DateTimeOffset）；不声明 IsDeleted（物理删除）。</para></summary>
public partial record CalendarEntityDto : IDomainDto<CalendarEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 日历编码（唯一，如 "Personal" / "Team"）。 </summary>
    public required string Code { get; init; }
    /// <summary> 日历名称。 </summary>
    public required string Name { get; init; }
    /// <summary> 描述。 </summary>
    public string? Description { get; init; }
    /// <summary> 颜色（Hex，如 "#3498DB"）。 </summary>
    public string? Color { get; init; }
    /// <summary> 是否启用（默认 true；GetOccurrencesAsync 默认排除禁用日历的事件，P3/D18）。 </summary>
    public bool IsEnabled { get; init; }
    /// <summary> 创建时间（UTC，显式声明）。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（UTC，显式声明）。 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static CalendarEntityDto FromEntity(CalendarEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new CalendarEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Code = entity.Code,
            Name = entity.Name,
            Description = entity.Description,
            Color = entity.Color,
            IsEnabled = entity.IsEnabled,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<CalendarEntity, CalendarEntityDto>> SelectExpression => e => new CalendarEntityDto
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        Description = e.Description,
        Color = e.Color,
        IsEnabled = e.IsEnabled,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    CalendarEntity IDomainDto<CalendarEntity>.ApplyToEntity(CalendarEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Code), d => d.Code, (e, v) => e.Code = v )
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(Description), d => d.Description, (e, v) => e.Description = v )
            .Map(nameof(Color), d => d.Color, (e, v) => e.Color = v )
            .Map(nameof(IsEnabled), d => d.IsEnabled, (e, v) => e.IsEnabled = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    CalendarEntity IDomainDto<CalendarEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(CalendarEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<CalendarEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<CalendarEntity, CalendarEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class CalendarEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static CalendarEntityDto ToDto(this CalendarEntity entity) => CalendarEntityDto.FromEntity(entity);
}

