// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 0f9c82c1ccb9ef994b85916736cb0161514fb60b0c3726274d271a5c84fbf7f3]
// 模型: TagHitRecordEntity (TKWF.Ext.Tagging.TagHitRecordEntity)
// 生成时间: 2026-09-14 08:06:12
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Tagging;

namespace TKWF.Ext.Tagging.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>TagHitRecordEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>TagHitRecordEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record TagHitRecordEntityDto : IDomainDto<TagHitRecordEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 维度。 </summary>
    public required string Dimension { get; init; }
    /// <summary> 标签名。 </summary>
    public required string TagName { get; init; }
    /// <summary> 命中原文片段。 </summary>
    public required string MatchedValue { get; init; }
    /// <summary> 命中起始位置。 </summary>
    public int StartIndex { get; init; }
    /// <summary> 命中长度。 </summary>
    public int Length { get; init; }
    /// <summary> 规则优先级。 </summary>
    public int Priority { get; init; }
    /// <summary> 互斥组。 </summary>
    public string? ExclusionGroup { get; init; }
    /// <summary> 原文快照（可选——分析上下文）。 </summary>
    public string? SourceText { get; init; }
    /// <summary> 命中时间（UTC——SQLite 可靠，Oracle P1-1；分析索引）。 </summary>
    public DateTime HitTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static TagHitRecordEntityDto FromEntity(TagHitRecordEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new TagHitRecordEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Dimension = entity.Dimension,
            TagName = entity.TagName,
            MatchedValue = entity.MatchedValue,
            StartIndex = entity.StartIndex,
            Length = entity.Length,
            Priority = entity.Priority,
            ExclusionGroup = entity.ExclusionGroup,
            SourceText = entity.SourceText,
            HitTime = entity.HitTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<TagHitRecordEntity, TagHitRecordEntityDto>> SelectExpression => e => new TagHitRecordEntityDto
    {
        Id = e.Id,
        Dimension = e.Dimension,
        TagName = e.TagName,
        MatchedValue = e.MatchedValue,
        StartIndex = e.StartIndex,
        Length = e.Length,
        Priority = e.Priority,
        ExclusionGroup = e.ExclusionGroup,
        SourceText = e.SourceText,
        HitTime = e.HitTime,
    };
    #endregion

    TagHitRecordEntity IDomainDto<TagHitRecordEntity>.ApplyToEntity(TagHitRecordEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Dimension), d => d.Dimension, (e, v) => e.Dimension = v )
            .Map(nameof(TagName), d => d.TagName, (e, v) => e.TagName = v )
            .Map(nameof(MatchedValue), d => d.MatchedValue, (e, v) => e.MatchedValue = v )
            .Map(nameof(StartIndex), d => d.StartIndex, (e, v) => e.StartIndex = v )
            .Map(nameof(Length), d => d.Length, (e, v) => e.Length = v )
            .Map(nameof(Priority), d => d.Priority, (e, v) => e.Priority = v )
            .Map(nameof(ExclusionGroup), d => d.ExclusionGroup, (e, v) => e.ExclusionGroup = v )
            .Map(nameof(SourceText), d => d.SourceText, (e, v) => e.SourceText = v )
            .Map(nameof(HitTime), d => d.HitTime, (e, v) => e.HitTime = v )
        ;
        return entity;
    }

    TagHitRecordEntity IDomainDto<TagHitRecordEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(TagHitRecordEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<TagHitRecordEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<TagHitRecordEntity, TagHitRecordEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class TagHitRecordEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static TagHitRecordEntityDto ToDto(this TagHitRecordEntity entity) => TagHitRecordEntityDto.FromEntity(entity);
}

