// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 4c36df8d6c8418e91b74bef6d2753fe0427d4751e3d0528ad060133e86daee10]
// 模型: RateLimitCounterEntity (TKWF.Ext.RateLimiting.RateLimitCounterEntity)
// 生成时间: 2026-10-07 18:43:46
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.RateLimiting;

namespace TKWF.Ext.RateLimiting.DTOs;
/// <summary>限流计数表实体——点检查原语（<c>IRateLimitCheck</c>）的 DB 持久化 Provider 计数底册。  <para>SG1 化：声明式实体——partial + <c>[DomainGenerateCode]</c>。</para>  <para>语义（方案 v0.3.0 §五 R2 / ADR-RateLimiting 决策点 2）：fixed window 单窗口计数器——Key 唯一，  窗口内 <c>Count</c> 经 ADR89 <c>UpdateWhereAsync</c> CAS 原子递增（<c>SET Count=Count+1 WHERE Key=@key AND  WindowEndUtc&gt;=@now AND Count&lt;@max</c>），跨实例 DB 行锁正确；首插靠 Key 唯一约束捕获并发冲突重试；  惰性淘汰（过期行随下一次命中重置，无后台清理——孤儿键增长 v0.2.0 清理任务）。</para>  <para>表名/索引 <c>TKWF_</c>/<c>TKWFIX_</c> 前缀（ADR100 表名前缀批次 A 已闭环——新表直接带前缀）。</para></summary>
public partial record RateLimitCounterEntityDto : IDomainDto<RateLimitCounterEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary>  </summary>
    public long Id { get; init; }
    /// <summary> 计数键（<c>{policy}:{partitionBy}:{subject}</c> 规范化——Provider 视为不透明字符串，仅作计数键；唯一索引 TKWFIX_RateLimitCounter_Key 类级声明）。 </summary>
    public required string Key { get; init; }
    /// <summary> 当前窗口内计数。 </summary>
    public int Count { get; init; }
    /// <summary> 窗口开始时刻（UTC）——语义锚定（GetRetryAfter 推导用）。 </summary>
    public DateTime WindowStartUtc { get; init; }
    /// <summary> 窗口结束时刻（UTC）——窗口过期判定（<c>WindowEndUtc &lt; now</c> → 重置）。 </summary>
    public DateTime WindowEndUtc { get; init; }
    /// <summary>  </summary>
    public DateTime CreateTime { get; init; }
    /// <summary>  </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static RateLimitCounterEntityDto FromEntity(RateLimitCounterEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new RateLimitCounterEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Key = entity.Key,
            Count = entity.Count,
            WindowStartUtc = entity.WindowStartUtc,
            WindowEndUtc = entity.WindowEndUtc,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<RateLimitCounterEntity, RateLimitCounterEntityDto>> SelectExpression => e => new RateLimitCounterEntityDto
    {
        Id = e.Id,
        Key = e.Key,
        Count = e.Count,
        WindowStartUtc = e.WindowStartUtc,
        WindowEndUtc = e.WindowEndUtc,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    RateLimitCounterEntity IDomainDto<RateLimitCounterEntity>.ApplyToEntity(RateLimitCounterEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Key), d => d.Key, (e, v) => e.Key = v )
            .Map(nameof(Count), d => d.Count, (e, v) => e.Count = v )
            .Map(nameof(WindowStartUtc), d => d.WindowStartUtc, (e, v) => e.WindowStartUtc = v )
            .Map(nameof(WindowEndUtc), d => d.WindowEndUtc, (e, v) => e.WindowEndUtc = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    RateLimitCounterEntity IDomainDto<RateLimitCounterEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(RateLimitCounterEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<RateLimitCounterEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<RateLimitCounterEntity, RateLimitCounterEntityDto>(scene, results)
                .MaxLength(nameof(Key), 256, d => d.Key)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class RateLimitCounterEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static RateLimitCounterEntityDto ToDto(this RateLimitCounterEntity entity) => RateLimitCounterEntityDto.FromEntity(entity);
}

