// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9b82e5a613f83ac2c5e8e3799f84fa49442c950d97900e4e4d5916ab66934694]
// 模型: TagHitRecordEntity (TKWF.Ext.Tagging.TagHitRecordEntity)
// 生成时间: 2026-09-14 08:06:12
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.Tagging;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>TagHitRecordEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>TagHitRecordEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class TagHitRecordEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：IXTagHitDimensionTime（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> ByIXTagHitDimensionTime(string dimension, DateTime? beginHitTime = null, DateTime? endHitTime = null)
        {
            return x => x.Dimension == dimension &&
            (!beginHitTime.HasValue || x.HitTime >= beginHitTime.Value) &&
            (!endHitTime.HasValue || x.HitTime <= endHitTime.Value);
        }

        /// <summary>模糊搜索：Dimension（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> LikeDimension(string? dimension = null)
        {
            if (string.IsNullOrEmpty(dimension)) return None;
            var val = dimension!;
            return x => x.Dimension.Contains(val);
        }
        /// <summary>多值模糊搜索：IXTagHitDimensionTime（按 Dimension Or-链）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> LikeIXTagHitDimensionTimeKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<TagHitRecordEntity>(x => x.Dimension, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：IXTagHitDimensionTime（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> EqualIXTagHitDimensionTime(string value)
        {
            return x => x.Dimension == value;
        }
        /// <summary>时间范围：HitTime（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> ByHitTimeRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.HitTime >= begin.Value)
                     && (!end.HasValue || x.HitTime <= end.Value);
        }
        /// <summary>组合条件：IXTagHitTagName（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> ByIXTagHitTagName(string tagName)
        {
            return x => x.TagName == tagName;
        }

        /// <summary>模糊搜索：TagName（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> LikeTagName(string? tagName = null)
        {
            if (string.IsNullOrEmpty(tagName)) return None;
            var val = tagName!;
            return x => x.TagName.Contains(val);
        }
        /// <summary>多值模糊搜索：IXTagHitTagName（按 TagName Or-链）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> LikeIXTagHitTagNameKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<TagHitRecordEntity>(x => x.TagName, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：IXTagHitTagName（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> EqualIXTagHitTagName(string value)
        {
            return x => x.TagName == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> All(params Expression<Func<TagHitRecordEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<TagHitRecordEntity, bool>> Any(params Expression<Func<TagHitRecordEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>TagHitRecordEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<TagHitRecordEntity>
    {

        /// <summary>组合条件：IXTagHitDimensionTime（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXTagHitDimensionTime(string dimension, DateTime? beginHitTime = null, DateTime? endHitTime = null)
            => (PredicateBuilder)Update(Conditions.ByIXTagHitDimensionTime(dimension, beginHitTime, endHitTime));

        /// <summary>模糊搜索：Dimension（单个关键字）</summary>
        public PredicateBuilder LikeDimension(string? dimension = null)
            => (PredicateBuilder)Update(Conditions.LikeDimension(dimension));

        /// <summary>多值模糊搜索：IXTagHitDimensionTime（按关键词 Or-链）</summary>
        public PredicateBuilder LikeIXTagHitDimensionTimeKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeIXTagHitDimensionTimeKeywords(keywords));

        /// <summary>跨属性精确匹配：IXTagHitDimensionTime（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualIXTagHitDimensionTime(string value)
            => (PredicateBuilder)Update(Conditions.EqualIXTagHitDimensionTime(value));

        /// <summary>时间范围：HitTime（begin/end 可选）</summary>
        public PredicateBuilder ByHitTimeRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByHitTimeRange(begin, end));

        /// <summary>组合条件：IXTagHitTagName（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXTagHitTagName(string tagName)
            => (PredicateBuilder)Update(Conditions.ByIXTagHitTagName(tagName));

        /// <summary>模糊搜索：TagName（单个关键字）</summary>
        public PredicateBuilder LikeTagName(string? tagName = null)
            => (PredicateBuilder)Update(Conditions.LikeTagName(tagName));

        /// <summary>多值模糊搜索：IXTagHitTagName（按关键词 Or-链）</summary>
        public PredicateBuilder LikeIXTagHitTagNameKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeIXTagHitTagNameKeywords(keywords));

        /// <summary>跨属性精确匹配：IXTagHitTagName（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualIXTagHitTagName(string value)
            => (PredicateBuilder)Update(Conditions.EqualIXTagHitTagName(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<TagHitRecordEntity> CreateBranch() => new PredicateBuilder();
}
}
