// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 2011c726ffe58f65dcbed3411817933b808d9aea846662ac7a5b3f78f9a95bb4]
// 模型: AuditLogEntity (TKWF.Ext.AuditLogging.AuditLogEntity)
// 生成时间: 2026-09-14 08:05:46
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.AuditLogging;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>AuditLogEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>AuditLogEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class AuditLogEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：IXAuditLogCorrelationId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<AuditLogEntity, bool>> ByIXAuditLogCorrelationId(string correlationId)
        {
            return x => x.CorrelationId == correlationId;
        }

        /// <summary>模糊搜索：CorrelationId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<AuditLogEntity, bool>> LikeCorrelationId(string? correlationId = null)
        {
            if (string.IsNullOrEmpty(correlationId)) return None;
            var val = correlationId!;
            return x => x.CorrelationId != null && x.CorrelationId.Contains(val);
        }
        /// <summary>多值模糊搜索：IXAuditLogCorrelationId（按 CorrelationId Or-链）</summary>
        public static Expression<Func<AuditLogEntity, bool>> LikeIXAuditLogCorrelationIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<AuditLogEntity>(x => x.CorrelationId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：IXAuditLogCorrelationId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<AuditLogEntity, bool>> EqualIXAuditLogCorrelationId(string value)
        {
            return x => x.CorrelationId == value;
        }
        /// <summary>组合条件：IXAuditLogExecutionTime（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<AuditLogEntity, bool>> ByIXAuditLogExecutionTime(DateTime? beginExecutionTime = null, DateTime? endExecutionTime = null)
        {
            return x => (!beginExecutionTime.HasValue || x.ExecutionTime >= beginExecutionTime.Value) &&
            (!endExecutionTime.HasValue || x.ExecutionTime <= endExecutionTime.Value);
        }

        /// <summary>时间范围：ExecutionTime（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<AuditLogEntity, bool>> ByExecutionTimeRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.ExecutionTime >= begin.Value)
                     && (!end.HasValue || x.ExecutionTime <= end.Value);
        }
        /// <summary>组合条件：IXAuditLogServiceName（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<AuditLogEntity, bool>> ByIXAuditLogServiceName(string serviceName)
        {
            return x => x.ServiceName == serviceName;
        }

        /// <summary>模糊搜索：ServiceName（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<AuditLogEntity, bool>> LikeServiceName(string? serviceName = null)
        {
            if (string.IsNullOrEmpty(serviceName)) return None;
            var val = serviceName!;
            return x => x.ServiceName.Contains(val);
        }
        /// <summary>多值模糊搜索：IXAuditLogServiceName（按 ServiceName Or-链）</summary>
        public static Expression<Func<AuditLogEntity, bool>> LikeIXAuditLogServiceNameKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<AuditLogEntity>(x => x.ServiceName, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：IXAuditLogServiceName（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<AuditLogEntity, bool>> EqualIXAuditLogServiceName(string value)
        {
            return x => x.ServiceName == value;
        }
        /// <summary>组合条件：IXAuditLogUserName（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<AuditLogEntity, bool>> ByIXAuditLogUserName(string userName)
        {
            return x => x.UserName == userName;
        }

        /// <summary>模糊搜索：UserName（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<AuditLogEntity, bool>> LikeUserName(string? userName = null)
        {
            if (string.IsNullOrEmpty(userName)) return None;
            var val = userName!;
            return x => x.UserName != null && x.UserName.Contains(val);
        }
        /// <summary>多值模糊搜索：IXAuditLogUserName（按 UserName Or-链）</summary>
        public static Expression<Func<AuditLogEntity, bool>> LikeIXAuditLogUserNameKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<AuditLogEntity>(x => x.UserName, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：IXAuditLogUserName（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<AuditLogEntity, bool>> EqualIXAuditLogUserName(string value)
        {
            return x => x.UserName == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<AuditLogEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<AuditLogEntity, bool>> All(params Expression<Func<AuditLogEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<AuditLogEntity, bool>> Any(params Expression<Func<AuditLogEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>AuditLogEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<AuditLogEntity>
    {

        /// <summary>组合条件：IXAuditLogCorrelationId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXAuditLogCorrelationId(string correlationId)
            => (PredicateBuilder)Update(Conditions.ByIXAuditLogCorrelationId(correlationId));

        /// <summary>模糊搜索：CorrelationId（单个关键字）</summary>
        public PredicateBuilder LikeCorrelationId(string? correlationId = null)
            => (PredicateBuilder)Update(Conditions.LikeCorrelationId(correlationId));

        /// <summary>多值模糊搜索：IXAuditLogCorrelationId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeIXAuditLogCorrelationIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeIXAuditLogCorrelationIdKeywords(keywords));

        /// <summary>跨属性精确匹配：IXAuditLogCorrelationId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualIXAuditLogCorrelationId(string value)
            => (PredicateBuilder)Update(Conditions.EqualIXAuditLogCorrelationId(value));

        /// <summary>组合条件：IXAuditLogExecutionTime（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXAuditLogExecutionTime(DateTime? beginExecutionTime = null, DateTime? endExecutionTime = null)
            => (PredicateBuilder)Update(Conditions.ByIXAuditLogExecutionTime(beginExecutionTime, endExecutionTime));

        /// <summary>时间范围：ExecutionTime（begin/end 可选）</summary>
        public PredicateBuilder ByExecutionTimeRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByExecutionTimeRange(begin, end));

        /// <summary>组合条件：IXAuditLogServiceName（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXAuditLogServiceName(string serviceName)
            => (PredicateBuilder)Update(Conditions.ByIXAuditLogServiceName(serviceName));

        /// <summary>模糊搜索：ServiceName（单个关键字）</summary>
        public PredicateBuilder LikeServiceName(string? serviceName = null)
            => (PredicateBuilder)Update(Conditions.LikeServiceName(serviceName));

        /// <summary>多值模糊搜索：IXAuditLogServiceName（按关键词 Or-链）</summary>
        public PredicateBuilder LikeIXAuditLogServiceNameKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeIXAuditLogServiceNameKeywords(keywords));

        /// <summary>跨属性精确匹配：IXAuditLogServiceName（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualIXAuditLogServiceName(string value)
            => (PredicateBuilder)Update(Conditions.EqualIXAuditLogServiceName(value));

        /// <summary>组合条件：IXAuditLogUserName（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXAuditLogUserName(string userName)
            => (PredicateBuilder)Update(Conditions.ByIXAuditLogUserName(userName));

        /// <summary>模糊搜索：UserName（单个关键字）</summary>
        public PredicateBuilder LikeUserName(string? userName = null)
            => (PredicateBuilder)Update(Conditions.LikeUserName(userName));

        /// <summary>多值模糊搜索：IXAuditLogUserName（按关键词 Or-链）</summary>
        public PredicateBuilder LikeIXAuditLogUserNameKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeIXAuditLogUserNameKeywords(keywords));

        /// <summary>跨属性精确匹配：IXAuditLogUserName（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualIXAuditLogUserName(string value)
            => (PredicateBuilder)Update(Conditions.EqualIXAuditLogUserName(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<AuditLogEntity> CreateBranch() => new PredicateBuilder();
}
}
