// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: b46f736c7b25298a49847561766db748f045b9c6f50a11554e83c6c8d1377d97]
// 模型: JobExecutionEntity (TKWF.Ext.BackgroundJobs.JobExecutionEntity)
// 生成时间: 2026-10-07 17:19:43
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.BackgroundJobs;

// V4.10.24 (G10): 实体类级 XML Doc 移入手写实体类（[DomainGenerateCode] partial 声明）——
// 此处不再给 partial class 写 <summary>（旧占位"条件工厂（V4.9）..."会被 Roslyn 合并进
// symbol.GetDocumentationCommentXml()，遮蔽手写实体描述）。条件工厂说明挪至 Conditions 嵌套类上方。
partial class JobExecutionEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    /// <summary>
    /// 条件工厂（V4.9）。支持两种使用方式：
    /// <list type="bullet">
    /// <item><c>JobExecutionEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
    /// <item><c>JobExecutionEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
    /// </list>
    /// </summary>
    public static class Conditions
    {
        /// <summary>组合条件：TKWFIXJobExecutionJobId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> ByTKWFIXJobExecutionJobId(string jobId)
        {
            return x => x.JobId == jobId;
        }

        /// <summary>模糊搜索：JobId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> LikeJobId(string? jobId = null)
        {
            if (string.IsNullOrEmpty(jobId)) return None;
            var val = jobId!;
            return x => x.JobId.Contains(val);
        }
        /// <summary>多值模糊搜索：TKWFIXJobExecutionJobId（按 JobId Or-链）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> LikeTKWFIXJobExecutionJobIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<JobExecutionEntity>(x => x.JobId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：TKWFIXJobExecutionJobId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> EqualTKWFIXJobExecutionJobId(string value)
        {
            return x => x.JobId == value;
        }
        /// <summary>组合条件：TKWFIXJobExecutionProviderSuccess（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> ByTKWFIXJobExecutionProviderSuccess(bool isSuccess, string provider)
        {
            return x => x.IsSuccess == isSuccess &&
            x.Provider == provider;
        }

        /// <summary>模糊搜索：Provider（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> LikeProvider(string? provider = null)
        {
            if (string.IsNullOrEmpty(provider)) return None;
            var val = provider!;
            return x => x.Provider.Contains(val);
        }
        /// <summary>多值模糊搜索：TKWFIXJobExecutionProviderSuccess（按 Provider Or-链）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> LikeTKWFIXJobExecutionProviderSuccessKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<JobExecutionEntity>(x => x.Provider, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：TKWFIXJobExecutionProviderSuccess（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> EqualTKWFIXJobExecutionProviderSuccess(string value)
        {
            return x => x.Provider == value;
        }
        /// <summary>组合条件：TKWFIXJobExecutionStartedAt（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> ByTKWFIXJobExecutionStartedAt(DateTime? beginStartedAtUtc = null, DateTime? endStartedAtUtc = null)
        {
            return x => (!beginStartedAtUtc.HasValue || x.StartedAtUtc >= beginStartedAtUtc.Value) &&
            (!endStartedAtUtc.HasValue || x.StartedAtUtc <= endStartedAtUtc.Value);
        }

        /// <summary>时间范围：StartedAtUtc（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> ByStartedAtUtcRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.StartedAtUtc >= begin.Value)
                     && (!end.HasValue || x.StartedAtUtc <= end.Value);
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<JobExecutionEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<JobExecutionEntity, bool>> All(params Expression<Func<JobExecutionEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<JobExecutionEntity, bool>> Any(params Expression<Func<JobExecutionEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>JobExecutionEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<JobExecutionEntity>
    {

        /// <summary>组合条件：TKWFIXJobExecutionJobId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTKWFIXJobExecutionJobId(string jobId)
            => (PredicateBuilder)Update(Conditions.ByTKWFIXJobExecutionJobId(jobId));

        /// <summary>模糊搜索：JobId（单个关键字）</summary>
        public PredicateBuilder LikeJobId(string? jobId = null)
            => (PredicateBuilder)Update(Conditions.LikeJobId(jobId));

        /// <summary>多值模糊搜索：TKWFIXJobExecutionJobId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeTKWFIXJobExecutionJobIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeTKWFIXJobExecutionJobIdKeywords(keywords));

        /// <summary>跨属性精确匹配：TKWFIXJobExecutionJobId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualTKWFIXJobExecutionJobId(string value)
            => (PredicateBuilder)Update(Conditions.EqualTKWFIXJobExecutionJobId(value));

        /// <summary>组合条件：TKWFIXJobExecutionProviderSuccess（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTKWFIXJobExecutionProviderSuccess(bool isSuccess, string provider)
            => (PredicateBuilder)Update(Conditions.ByTKWFIXJobExecutionProviderSuccess(isSuccess, provider));

        /// <summary>模糊搜索：Provider（单个关键字）</summary>
        public PredicateBuilder LikeProvider(string? provider = null)
            => (PredicateBuilder)Update(Conditions.LikeProvider(provider));

        /// <summary>多值模糊搜索：TKWFIXJobExecutionProviderSuccess（按关键词 Or-链）</summary>
        public PredicateBuilder LikeTKWFIXJobExecutionProviderSuccessKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeTKWFIXJobExecutionProviderSuccessKeywords(keywords));

        /// <summary>跨属性精确匹配：TKWFIXJobExecutionProviderSuccess（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualTKWFIXJobExecutionProviderSuccess(string value)
            => (PredicateBuilder)Update(Conditions.EqualTKWFIXJobExecutionProviderSuccess(value));

        /// <summary>组合条件：TKWFIXJobExecutionStartedAt（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTKWFIXJobExecutionStartedAt(DateTime? beginStartedAtUtc = null, DateTime? endStartedAtUtc = null)
            => (PredicateBuilder)Update(Conditions.ByTKWFIXJobExecutionStartedAt(beginStartedAtUtc, endStartedAtUtc));

        /// <summary>时间范围：StartedAtUtc（begin/end 可选）</summary>
        public PredicateBuilder ByStartedAtUtcRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByStartedAtUtcRange(begin, end));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<JobExecutionEntity> CreateBranch() => new PredicateBuilder();
}
}
