// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: bd56e52c2dc8832da98cfab9dbb3b9071e30f1530e1d3e7d0fe3e390faf5db43]
// 模型: JobResultEntity (TKWF.Ext.BackgroundJobs.JobResultEntity)
// 生成时间: 2026-10-07 17:19:43
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.BackgroundJobs;

// V4.10.24 (G10): 实体类级 XML Doc 移入手写实体类（[DomainGenerateCode] partial 声明）——
// 此处不再给 partial class 写 <summary>（旧占位"条件工厂（V4.9）..."会被 Roslyn 合并进
// symbol.GetDocumentationCommentXml()，遮蔽手写实体描述）。条件工厂说明挪至 Conditions 嵌套类上方。
partial class JobResultEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    /// <summary>
    /// 条件工厂（V4.9）。支持两种使用方式：
    /// <list type="bullet">
    /// <item><c>JobResultEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
    /// <item><c>JobResultEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
    /// </list>
    /// </summary>
    public static class Conditions
    {
        /// <summary>组合条件：TKWFIXJobResultCreateTime（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<JobResultEntity, bool>> ByTKWFIXJobResultCreateTime(DateTime? beginCreateTime = null, DateTime? endCreateTime = null)
        {
            return x => (!beginCreateTime.HasValue || x.CreateTime >= beginCreateTime.Value) &&
            (!endCreateTime.HasValue || x.CreateTime <= endCreateTime.Value);
        }

        /// <summary>时间范围：CreateTime（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<JobResultEntity, bool>> ByCreateTimeRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.CreateTime >= begin.Value)
                     && (!end.HasValue || x.CreateTime <= end.Value);
        }
        /// <summary>组合条件：TKWFIXJobResultJobId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<JobResultEntity, bool>> ByTKWFIXJobResultJobId(string jobId)
        {
            return x => x.JobId == jobId;
        }

        /// <summary>模糊搜索：JobId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<JobResultEntity, bool>> LikeJobId(string? jobId = null)
        {
            if (string.IsNullOrEmpty(jobId)) return None;
            var val = jobId!;
            return x => x.JobId.Contains(val);
        }
        /// <summary>多值模糊搜索：TKWFIXJobResultJobId（按 JobId Or-链）</summary>
        public static Expression<Func<JobResultEntity, bool>> LikeTKWFIXJobResultJobIdKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<JobResultEntity>(x => x.JobId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：TKWFIXJobResultJobId（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<JobResultEntity, bool>> EqualTKWFIXJobResultJobId(string value)
        {
            return x => x.JobId == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<JobResultEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<JobResultEntity, bool>> All(params Expression<Func<JobResultEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<JobResultEntity, bool>> Any(params Expression<Func<JobResultEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>JobResultEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<JobResultEntity>
    {

        /// <summary>组合条件：TKWFIXJobResultCreateTime（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTKWFIXJobResultCreateTime(DateTime? beginCreateTime = null, DateTime? endCreateTime = null)
            => (PredicateBuilder)Update(Conditions.ByTKWFIXJobResultCreateTime(beginCreateTime, endCreateTime));

        /// <summary>时间范围：CreateTime（begin/end 可选）</summary>
        public PredicateBuilder ByCreateTimeRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByCreateTimeRange(begin, end));

        /// <summary>组合条件：TKWFIXJobResultJobId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTKWFIXJobResultJobId(string jobId)
            => (PredicateBuilder)Update(Conditions.ByTKWFIXJobResultJobId(jobId));

        /// <summary>模糊搜索：JobId（单个关键字）</summary>
        public PredicateBuilder LikeJobId(string? jobId = null)
            => (PredicateBuilder)Update(Conditions.LikeJobId(jobId));

        /// <summary>多值模糊搜索：TKWFIXJobResultJobId（按关键词 Or-链）</summary>
        public PredicateBuilder LikeTKWFIXJobResultJobIdKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeTKWFIXJobResultJobIdKeywords(keywords));

        /// <summary>跨属性精确匹配：TKWFIXJobResultJobId（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualTKWFIXJobResultJobId(string value)
            => (PredicateBuilder)Update(Conditions.EqualTKWFIXJobResultJobId(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<JobResultEntity> CreateBranch() => new PredicateBuilder();
}
}
