// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 3a6afe5e7ea5a52e1c8ac716db885a3d80bf8ea3816e5859c87e518c5b419b9f]
// 模型: ManagedFileVersionEntity (TKWF.Ext.FileManagement.ManagedFileVersionEntity)
// 生成时间: 2026-09-16 05:51:53
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.FileManagement;

// V4.10.24 (G10): 实体类级 XML Doc 移入手写实体类（[DomainGenerateCode] partial 声明）——
// 此处不再给 partial class 写 <summary>（旧占位"条件工厂（V4.9）..."会被 Roslyn 合并进
// symbol.GetDocumentationCommentXml()，遮蔽手写实体描述）。条件工厂说明挪至 Conditions 嵌套类上方。
partial class ManagedFileVersionEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    /// <summary>
    /// 条件工厂（V4.9）。支持两种使用方式：
    /// <list type="bullet">
    /// <item><c>ManagedFileVersionEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
    /// <item><c>ManagedFileVersionEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
    /// </list>
    /// </summary>
    public static class Conditions
    {
        /// <summary>组合条件：IXMfvFile（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<ManagedFileVersionEntity, bool>> ByIXMfvFile(long fileId)
        {
            return x => x.FileId == fileId;
        }

        /// <summary>精确匹配：UXMfvFileVersion（Unique 索引，必填参数）</summary>
        public static Expression<Func<ManagedFileVersionEntity, bool>> ByUXMfvFileVersion(long fileId, int version)
            => x => x.FileId == fileId && x.Version == version;

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<ManagedFileVersionEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<ManagedFileVersionEntity, bool>> All(params Expression<Func<ManagedFileVersionEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<ManagedFileVersionEntity, bool>> Any(params Expression<Func<ManagedFileVersionEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>ManagedFileVersionEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<ManagedFileVersionEntity>
    {

        /// <summary>组合条件：IXMfvFile（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXMfvFile(long fileId)
            => (PredicateBuilder)Update(Conditions.ByIXMfvFile(fileId));

        /// <summary>精确匹配：UXMfvFileVersion（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByUXMfvFileVersion(long fileId, int version)
            => (PredicateBuilder)Update(Conditions.ByUXMfvFileVersion(fileId, version));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<ManagedFileVersionEntity> CreateBranch() => new PredicateBuilder();
}
}
