<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>TKWF.Federation.Google.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Microsoft.Extensions.DependencyInjection.Extensions" />
    <Using Include="Microsoft.Extensions.Options" />
    <Using Include="TKW.Framework.Domain.Interfaces" />
    <Using Include="TKW.Framework.Domain.Hosting" />
    <Using Include="TKW.Framework.Core.Hosting" />
    <Using Include="TKW.Framework.Domain.Session" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\_Framework\Federation.Google\TKWF.Federation.Google.csproj" />
    <ProjectReference Include="..\..\_Framework\Federation.Oidc\TKWF.Federation.Oidc.csproj" />
    <ProjectReference Include="..\..\_Framework\Federation\TKWF.Ext.Federation.csproj" />
    <ProjectReference Include="..\Extension.Testing.Shared\TKWF.Ext.Testing.Shared.csproj" />
    <PackageReference Include="TKWF.Core" Condition="'$(UseLocalFw)' != 'true'" />
    <PackageReference Include="TKWF.Domain" Condition="'$(UseLocalFw)' != 'true'" />
    <Reference Include="TKWF.CodeGeneration.Abstractions" HintPath="$(_LocalFwRefsDir)TKWF.CodeGeneration.Abstractions.dll" Condition="'$(UseLocalFw)' == 'true' And Exists('$(_LocalFwRefsDir)TKWF.CodeGeneration.Abstractions.dll')" />
    <PackageReference Include="TKWF.CodeGeneration.Abstractions" Condition="'$(UseLocalFw)' != 'true'" />
  </ItemGroup>

</Project>