// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 78b8503b847e97e764f958f0b4fd15c2ada3d3b7ce80e3a28ba558c36b388005]
// 模型: SecurityLogEntity (TKWF.Ext.SecurityLog.SecurityLogEntity)
// 生成时间: 2026-10-07 17:20:05
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.SecurityLog;

// V4.10.24 (G10): 实体类级 XML Doc 移入手写实体类（[DomainGenerateCode] partial 声明）——
// 此处不再给 partial class 写 <summary>（旧占位"条件工厂（V4.9）..."会被 Roslyn 合并进
// symbol.GetDocumentationCommentXml()，遮蔽手写实体描述）。条件工厂说明挪至 Conditions 嵌套类上方。
partial class SecurityLogEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    /// <summary>
    /// 条件工厂（V4.9）。支持两种使用方式：
    /// <list type="bullet">
    /// <item><c>SecurityLogEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
    /// <item><c>SecurityLogEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
    /// </list>
    /// </summary>
    public static class Conditions
    {
        /// <summary>组合条件：TKWFIXSecurityLogIpTime（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> ByTKWFIXSecurityLogIpTime(string ipAddress, DateTime? beginCreateTime = null, DateTime? endCreateTime = null)
        {
            return x => x.IpAddress == ipAddress &&
            (!beginCreateTime.HasValue || x.CreateTime >= beginCreateTime.Value) &&
            (!endCreateTime.HasValue || x.CreateTime <= endCreateTime.Value);
        }

        /// <summary>模糊搜索：IpAddress（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> LikeIpAddress(string? ipAddress = null)
        {
            if (string.IsNullOrEmpty(ipAddress)) return None;
            var val = ipAddress!;
            return x => x.IpAddress != null && x.IpAddress.Contains(val);
        }
        /// <summary>多值模糊搜索：TKWFIXSecurityLogIpTime（按 IpAddress Or-链）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> LikeTKWFIXSecurityLogIpTimeKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<SecurityLogEntity>(x => x.IpAddress, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：TKWFIXSecurityLogIpTime（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> EqualTKWFIXSecurityLogIpTime(string value)
        {
            return x => x.IpAddress == value;
        }
        /// <summary>时间范围：CreateTime（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> ByCreateTimeRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.CreateTime >= begin.Value)
                     && (!end.HasValue || x.CreateTime <= end.Value);
        }
        /// <summary>组合条件：TKWFIXSecurityLogUserEventTime（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> ByTKWFIXSecurityLogUserEventTime(string eventType, string userName, DateTime? beginCreateTime = null, DateTime? endCreateTime = null)
        {
            return x => x.EventType == eventType &&
            x.UserName == userName &&
            (!beginCreateTime.HasValue || x.CreateTime >= beginCreateTime.Value) &&
            (!endCreateTime.HasValue || x.CreateTime <= endCreateTime.Value);
        }

        /// <summary>模糊搜索：EventType（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> LikeEventType(string? eventType = null)
        {
            if (string.IsNullOrEmpty(eventType)) return None;
            var val = eventType!;
            return x => x.EventType.Contains(val);
        }
        /// <summary>模糊搜索：UserName（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> LikeUserName(string? userName = null)
        {
            if (string.IsNullOrEmpty(userName)) return None;
            var val = userName!;
            return x => x.UserName.Contains(val);
        }
        /// <summary>多值模糊搜索：TKWFIXSecurityLogUserEventTime（按 EventType Or-链）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> LikeTKWFIXSecurityLogUserEventTimeKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<SecurityLogEntity>(x => x.EventType, keywords) ?? None;
        }
        /// <summary>跨属性模糊搜索：TKWFIXSecurityLogUserEventTime（单个关键字在多个字符串属性中 OR 匹配）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> LikeTKWFIXSecurityLogUserEventTime(string? keyword = null)
        {
            if (string.IsNullOrEmpty(keyword)) return None;
            var kw = keyword!;
            return x => x.EventType.Contains(kw) ||
                x.UserName.Contains(kw);
        }
        /// <summary>跨属性精确匹配：TKWFIXSecurityLogUserEventTime（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> EqualTKWFIXSecurityLogUserEventTime(string value)
        {
            return x => x.EventType == value ||
                x.UserName == value;
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<SecurityLogEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<SecurityLogEntity, bool>> All(params Expression<Func<SecurityLogEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<SecurityLogEntity, bool>> Any(params Expression<Func<SecurityLogEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>SecurityLogEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<SecurityLogEntity>
    {

        /// <summary>组合条件：TKWFIXSecurityLogIpTime（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTKWFIXSecurityLogIpTime(string ipAddress, DateTime? beginCreateTime = null, DateTime? endCreateTime = null)
            => (PredicateBuilder)Update(Conditions.ByTKWFIXSecurityLogIpTime(ipAddress, beginCreateTime, endCreateTime));

        /// <summary>模糊搜索：IpAddress（单个关键字）</summary>
        public PredicateBuilder LikeIpAddress(string? ipAddress = null)
            => (PredicateBuilder)Update(Conditions.LikeIpAddress(ipAddress));

        /// <summary>多值模糊搜索：TKWFIXSecurityLogIpTime（按关键词 Or-链）</summary>
        public PredicateBuilder LikeTKWFIXSecurityLogIpTimeKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeTKWFIXSecurityLogIpTimeKeywords(keywords));

        /// <summary>跨属性精确匹配：TKWFIXSecurityLogIpTime（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualTKWFIXSecurityLogIpTime(string value)
            => (PredicateBuilder)Update(Conditions.EqualTKWFIXSecurityLogIpTime(value));

        /// <summary>时间范围：CreateTime（begin/end 可选）</summary>
        public PredicateBuilder ByCreateTimeRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByCreateTimeRange(begin, end));

        /// <summary>组合条件：TKWFIXSecurityLogUserEventTime（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByTKWFIXSecurityLogUserEventTime(string eventType, string userName, DateTime? beginCreateTime = null, DateTime? endCreateTime = null)
            => (PredicateBuilder)Update(Conditions.ByTKWFIXSecurityLogUserEventTime(eventType, userName, beginCreateTime, endCreateTime));

        /// <summary>模糊搜索：EventType（单个关键字）</summary>
        public PredicateBuilder LikeEventType(string? eventType = null)
            => (PredicateBuilder)Update(Conditions.LikeEventType(eventType));

        /// <summary>模糊搜索：UserName（单个关键字）</summary>
        public PredicateBuilder LikeUserName(string? userName = null)
            => (PredicateBuilder)Update(Conditions.LikeUserName(userName));

        /// <summary>多值模糊搜索：TKWFIXSecurityLogUserEventTime（按关键词 Or-链）</summary>
        public PredicateBuilder LikeTKWFIXSecurityLogUserEventTimeKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeTKWFIXSecurityLogUserEventTimeKeywords(keywords));

        /// <summary>跨属性模糊搜索：TKWFIXSecurityLogUserEventTime（单个关键字在多个字符串属性中 OR 匹配）</summary>
        public PredicateBuilder LikeTKWFIXSecurityLogUserEventTime(string? keyword = null)
            => (PredicateBuilder)Update(Conditions.LikeTKWFIXSecurityLogUserEventTime(keyword));

        /// <summary>跨属性精确匹配：TKWFIXSecurityLogUserEventTime（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualTKWFIXSecurityLogUserEventTime(string value)
            => (PredicateBuilder)Update(Conditions.EqualTKWFIXSecurityLogUserEventTime(value));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<SecurityLogEntity> CreateBranch() => new PredicateBuilder();
}
}
