// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 4e1fcfc0d2027762cf3f26d0d71b864294cab6b85fc0565eec70104539a5aa29]
// 模型: PrintTemplateEntity (TKWF.Ext.PrintTemplates.PrintTemplateEntity)
// 生成时间: 2026-09-14 08:06:07
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.PrintTemplates;

namespace TKWF.Ext.PrintTemplates.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>PrintTemplateEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>PrintTemplateEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record PrintTemplateEntityDto : IDomainDto<PrintTemplateEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 模板键（唯一，如 "Invoice.Standard"）。 </summary>
    public required string Key { get; init; }
    /// <summary> 显示名（如 "标准发票"）。 </summary>
    public required string Name { get; init; }
    /// <summary> 描述。 </summary>
    public string? Description { get; init; }
    /// <summary> 创建时间。 </summary>
    public required DateTimeOffset CreateTime { get; init; }
    /// <summary> 更新时间。 </summary>
    public required DateTimeOffset UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static PrintTemplateEntityDto FromEntity(PrintTemplateEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new PrintTemplateEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Key = entity.Key,
            Name = entity.Name,
            Description = entity.Description,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<PrintTemplateEntity, PrintTemplateEntityDto>> SelectExpression => e => new PrintTemplateEntityDto
    {
        Id = e.Id,
        Key = e.Key,
        Name = e.Name,
        Description = e.Description,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    PrintTemplateEntity IDomainDto<PrintTemplateEntity>.ApplyToEntity(PrintTemplateEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Key), d => d.Key, (e, v) => e.Key = v )
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(Description), d => d.Description, (e, v) => e.Description = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    PrintTemplateEntity IDomainDto<PrintTemplateEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(PrintTemplateEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<PrintTemplateEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<PrintTemplateEntity, PrintTemplateEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class PrintTemplateEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static PrintTemplateEntityDto ToDto(this PrintTemplateEntity entity) => PrintTemplateEntityDto.FromEntity(entity);
}

