// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: e68a64ccd4776022014fee38ab2afb01e8e602ca6f164c48528657328fbcd48a]
// 模型: CalendarEventEntity (TKWF.Ext.Calendar.CalendarEventEntity)
// 生成时间: 2026-09-14 08:05:51
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.Calendar;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>CalendarEventEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>CalendarEventEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class CalendarEventEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：IXCalendarEventCalendarIdRecurrenceEndUtc（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<CalendarEventEntity, bool>> ByIXCalendarEventCalendarIdRecurrenceEndUtc(long calendarId, DateTime? beginRecurrenceEndUtc = null, DateTime? endRecurrenceEndUtc = null)
        {
            return x => x.CalendarId == calendarId &&
            (!beginRecurrenceEndUtc.HasValue || x.RecurrenceEndUtc >= beginRecurrenceEndUtc.Value) &&
            (!endRecurrenceEndUtc.HasValue || x.RecurrenceEndUtc <= endRecurrenceEndUtc.Value);
        }

        /// <summary>时间范围：RecurrenceEndUtc（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<CalendarEventEntity, bool>> ByRecurrenceEndUtcRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.RecurrenceEndUtc >= begin.Value)
                     && (!end.HasValue || x.RecurrenceEndUtc <= end.Value);
        }
        /// <summary>组合条件：IXCalendarEventCalendarIdStartUtc（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<CalendarEventEntity, bool>> ByIXCalendarEventCalendarIdStartUtc(long calendarId, DateTime? beginStartUtc = null, DateTime? endStartUtc = null)
        {
            return x => x.CalendarId == calendarId &&
            (!beginStartUtc.HasValue || x.StartUtc >= beginStartUtc.Value) &&
            (!endStartUtc.HasValue || x.StartUtc <= endStartUtc.Value);
        }

        /// <summary>时间范围：StartUtc（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<CalendarEventEntity, bool>> ByStartUtcRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.StartUtc >= begin.Value)
                     && (!end.HasValue || x.StartUtc <= end.Value);
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<CalendarEventEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<CalendarEventEntity, bool>> All(params Expression<Func<CalendarEventEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<CalendarEventEntity, bool>> Any(params Expression<Func<CalendarEventEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>CalendarEventEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<CalendarEventEntity>
    {

        /// <summary>组合条件：IXCalendarEventCalendarIdRecurrenceEndUtc（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXCalendarEventCalendarIdRecurrenceEndUtc(long calendarId, DateTime? beginRecurrenceEndUtc = null, DateTime? endRecurrenceEndUtc = null)
            => (PredicateBuilder)Update(Conditions.ByIXCalendarEventCalendarIdRecurrenceEndUtc(calendarId, beginRecurrenceEndUtc, endRecurrenceEndUtc));

        /// <summary>时间范围：RecurrenceEndUtc（begin/end 可选）</summary>
        public PredicateBuilder ByRecurrenceEndUtcRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByRecurrenceEndUtcRange(begin, end));

        /// <summary>组合条件：IXCalendarEventCalendarIdStartUtc（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXCalendarEventCalendarIdStartUtc(long calendarId, DateTime? beginStartUtc = null, DateTime? endStartUtc = null)
            => (PredicateBuilder)Update(Conditions.ByIXCalendarEventCalendarIdStartUtc(calendarId, beginStartUtc, endStartUtc));

        /// <summary>时间范围：StartUtc（begin/end 可选）</summary>
        public PredicateBuilder ByStartUtcRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByStartUtcRange(begin, end));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<CalendarEventEntity> CreateBranch() => new PredicateBuilder();
}
}
