// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 714d9e534a1ff3f9da5ff6310093183d49e1d6aab401fcf1edf308b6646b8d92]
// 模型: AccountLockoutEntity (TKWF.Ext.Account.AccountLockoutEntity)
// 生成时间: 2026-09-14 08:05:44
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Account;

namespace TKWF.Ext.Account.DTOs;
/// <summary>账户锁定记录——用户名、失败计数与锁定截止时间。     <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>；     保留 BCL <c>[Table("AccountLockout")]</c>；列映射用 FreeSql <c>[Column]</c>。</para></summary>
public partial record AccountLockoutEntityDto : IDomainDto<AccountLockoutEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 用户名（唯一）。 </summary>
    public required string UserName { get; init; }
    /// <summary> 连续失败次数。 </summary>
    public int FailedCount { get; init; }
    /// <summary> 锁定截止时间（null = 未锁定）。 </summary>
    public DateTime? LockoutEnd { get; init; }
    /// <summary> 最近失败时间。 </summary>
    public DateTime? LastFailedTime { get; init; }
    /// <summary> 创建时间。 </summary>
    public required DateTimeOffset CreateTime { get; init; }
    /// <summary> 更新时间。 </summary>
    public required DateTimeOffset UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static AccountLockoutEntityDto FromEntity(AccountLockoutEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new AccountLockoutEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UserName = entity.UserName,
            FailedCount = entity.FailedCount,
            LockoutEnd = entity.LockoutEnd,
            LastFailedTime = entity.LastFailedTime,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<AccountLockoutEntity, AccountLockoutEntityDto>> SelectExpression => e => new AccountLockoutEntityDto
    {
        Id = e.Id,
        UserName = e.UserName,
        FailedCount = e.FailedCount,
        LockoutEnd = e.LockoutEnd,
        LastFailedTime = e.LastFailedTime,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    AccountLockoutEntity IDomainDto<AccountLockoutEntity>.ApplyToEntity(AccountLockoutEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UserName), d => d.UserName, (e, v) => e.UserName = v )
            .Map(nameof(FailedCount), d => d.FailedCount, (e, v) => e.FailedCount = v )
            .Map(nameof(LockoutEnd), d => d.LockoutEnd, (e, v) => e.LockoutEnd = v )
            .Map(nameof(LastFailedTime), d => d.LastFailedTime, (e, v) => e.LastFailedTime = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    AccountLockoutEntity IDomainDto<AccountLockoutEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(AccountLockoutEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<AccountLockoutEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<AccountLockoutEntity, AccountLockoutEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class AccountLockoutEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static AccountLockoutEntityDto ToDto(this AccountLockoutEntity entity) => AccountLockoutEntityDto.FromEntity(entity);
}

