// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: dd31de778b3fcc4011e3c73bea6d373e49d7761013f3c9c8fdc63d684b2f2aee]
// 模型: TestMetricResultEntity (TKWF.Ext.Metrics.Tests.TestMetricResultEntity)
// 生成时间: 2026-09-14 08:19:47
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Metrics.Tests;

namespace TKWF.Ext.Metrics.Tests.DTOs;
/// <summary>测试持久化实体——模拟消费方定义的指标结果表（v0.2.0 持久化契约消费方实体）。     <para>消费方实体由 <c>partial class</c> + <c>[Table]</c> + <c>[DomainGenerateCode]</c> 声明（SG1/xCodeGen     自动生成 IDomainEntity 部分、DTO/DataService——对齐扩展项目固有模式）；本测试项目<b>首次</b>在测试宿主内     定义 <c>[DomainGenerateCode]</c> 实体（模拟消费方接线，方案 §四 T0）。     若 SG1 生成器不识别测试项目（编译失败），按方案替代路径：移除 <c>[DomainGenerateCode]</c>、     手写 <c>IDomainEntity</c> 分部实现 + 手写 DataService 分部子类（见 <c>TestMetricResultEntityDataService</c> 注释）。</para>     <para>表结构对齐方案 §3.4 示例：Id 主键自增 / SpecKey / Name / ValueText（JSON 化值）/ Unit /     DimensionsJson / CalculatedAtUtc / CreateTime。</para></summary>
public partial record TestMetricResultEntityDto : IDomainDto<TestMetricResultEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 规格键（如 "sales"），可空。 </summary>
    public string? SpecKey { get; init; }
    /// <summary> 指标名（如 "repurchase-rate-30d"）。 </summary>
    public required string Name { get; init; }
    /// <summary> 值（JSON 化文本；标量 ToString / string 直通 / 复杂对象 JSON——TestMetricResultStore switch 三路径）。 </summary>
    public string? ValueText { get; init; }
    /// <summary> 单位（如 "%"、"CNY"），可空。 </summary>
    public string? Unit { get; init; }
    /// <summary> 维度 JSON（如 {"bucket":"2026-08-01"}），可空。 </summary>
    public string? DimensionsJson { get; init; }
    /// <summary> 计算时间（UTC）。 </summary>
    public DateTime CalculatedAtUtc { get; init; }
    /// <summary> 记录创建时间。 </summary>
    public DateTime CreateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static TestMetricResultEntityDto FromEntity(TestMetricResultEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new TestMetricResultEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            SpecKey = entity.SpecKey,
            Name = entity.Name,
            ValueText = entity.ValueText,
            Unit = entity.Unit,
            DimensionsJson = entity.DimensionsJson,
            CalculatedAtUtc = entity.CalculatedAtUtc,
            CreateTime = entity.CreateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<TestMetricResultEntity, TestMetricResultEntityDto>> SelectExpression => e => new TestMetricResultEntityDto
    {
        Id = e.Id,
        SpecKey = e.SpecKey,
        Name = e.Name,
        ValueText = e.ValueText,
        Unit = e.Unit,
        DimensionsJson = e.DimensionsJson,
        CalculatedAtUtc = e.CalculatedAtUtc,
        CreateTime = e.CreateTime,
    };
    #endregion

    TestMetricResultEntity IDomainDto<TestMetricResultEntity>.ApplyToEntity(TestMetricResultEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(SpecKey), d => d.SpecKey, (e, v) => e.SpecKey = v )
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(ValueText), d => d.ValueText, (e, v) => e.ValueText = v )
            .Map(nameof(Unit), d => d.Unit, (e, v) => e.Unit = v )
            .Map(nameof(DimensionsJson), d => d.DimensionsJson, (e, v) => e.DimensionsJson = v )
            .Map(nameof(CalculatedAtUtc), d => d.CalculatedAtUtc, (e, v) => e.CalculatedAtUtc = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
        ;
        return entity;
    }

    TestMetricResultEntity IDomainDto<TestMetricResultEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(TestMetricResultEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<TestMetricResultEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<TestMetricResultEntity, TestMetricResultEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class TestMetricResultEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static TestMetricResultEntityDto ToDto(this TestMetricResultEntity entity) => TestMetricResultEntityDto.FromEntity(entity);
}

