// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: e615b3e7aa1023caec070e16448581763c9d9885748e814d7446acdc84c34f91]
// 模型: MfaRecoveryCodeEntity (TKWF.Ext.MFA.MfaRecoveryCodeEntity)
// 生成时间: 2026-10-01 06:12:39
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.MFA;

namespace TKWF.Ext.MFA.DTOs;
/// <summary>MFA 恢复码实体——防锁死（验证器/手机丢失时凭恢复码解绑重绑）。  <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>；保留 BCL <c>[Table("TKWF_MfaRecoveryCode")]</c>；  列映射用 FreeSql <c>[Column]</c>（全限定）。</para>  <para>恢复码语义：8 位字母数字（去易混淆字符 0/O/1/I/l，Oracle P9）SHA256 落库（明文不落库）、单次消费  （<c>IsConsumed</c> 翻转）、再生成 = 全量替换（删旧码插新码）；验证纳入 per-user×method 频控（Oracle C4）。</para>  <para>索引：<c>UX_MfaRecovery_User_CodeHash</c>（UserId+CodeHash 联合唯一——码唯一防碰撞）。</para></summary>
public partial record MfaRecoveryCodeEntityDto : IDomainDto<MfaRecoveryCodeEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 归属用户 Id。 </summary>
    public required string UserId { get; init; }
    /// <summary> 是否已消费（使用后翻转 true——单次消费，Oracle C1）。 </summary>
    public bool IsConsumed { get; init; }
    /// <summary> 创建时间（UTC，CanUpdate=false）。 </summary>
    public DateTime CreateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static MfaRecoveryCodeEntityDto FromEntity(MfaRecoveryCodeEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new MfaRecoveryCodeEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UserId = entity.UserId,
            IsConsumed = entity.IsConsumed,
            CreateTime = entity.CreateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<MfaRecoveryCodeEntity, MfaRecoveryCodeEntityDto>> SelectExpression => e => new MfaRecoveryCodeEntityDto
    {
        Id = e.Id,
        UserId = e.UserId,
        IsConsumed = e.IsConsumed,
        CreateTime = e.CreateTime,
    };
    #endregion

    MfaRecoveryCodeEntity IDomainDto<MfaRecoveryCodeEntity>.ApplyToEntity(MfaRecoveryCodeEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(IsConsumed), d => d.IsConsumed, (e, v) => e.IsConsumed = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
        ;
        return entity;
    }

    MfaRecoveryCodeEntity IDomainDto<MfaRecoveryCodeEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(MfaRecoveryCodeEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<MfaRecoveryCodeEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<MfaRecoveryCodeEntity, MfaRecoveryCodeEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class MfaRecoveryCodeEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static MfaRecoveryCodeEntityDto ToDto(this MfaRecoveryCodeEntity entity) => MfaRecoveryCodeEntityDto.FromEntity(entity);
}

