// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9715e22a2b4dd9c4a3c3578f2b249f28a91162843fefce01807f494dbcaa0635]
// 模型: UserOrganizationUnitView (TKWF.Ext.OrganizationUnit.UserOrganizationUnitView)
// 生成时间: 2026-10-01 02:34:16
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.OrganizationUnit;

namespace TKWF.Ext.OrganizationUnit.DTOs;
/// <summary>组织单元-用户关联视图实体（VEntity）——跨表 JOIN <c>OrganizationUnitUser</c> → <c>OrganizationUnit</c>，  按 OUPath 前缀单查询返回用户归属 + OU 列（读模型联邦，V0.2.0 下推）。  <para>V0.2.0：替代 <c>GetUserIdsInOrganizationUnitAsync(includeDescendants: true)</c> 两步查询  （先取子树 OU Id 集合 → 再 junction 查 UserIds）——JOIN + Path 前缀谓词下推 DB，单查询完成。  VEntity 只读：<c>IDomainViewEntity</c> 由 SG1 自动生成，禁 IEntityDAC 写操作。  ⚠️ 敏感视图（含用户归属明细）：ExposeGraphqlQuery = false，数据访问统一经 IOrganizationUnitManager 门面。</para></summary>
public partial record UserOrganizationUnitViewDto : IDomainDto<UserOrganizationUnitView>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键——透传 OrganizationUnitUser.Id（每关联行唯一稳定）。 </summary>
    public long Id { get; init; }
    /// <summary> 组织单元 Id（外层过滤键，视图外参数化）。 </summary>
    public long OrganizationUnitId { get; init; }
    /// <summary> 用户 Id（string，对齐 IUserInfo.UserIdString）。 </summary>
    public required string UserId { get; init; }
    /// <summary> 组织单元物化路径（透传 OU.Path，前缀过滤键——精确前缀比较，非 LIKE，见 GetByPathPrefixAsync 实证注记）。 </summary>
    public required string OUPath { get; init; }
    /// <summary> 组织单元编码（透传 OU.Code，白名单 [A-Za-z0-9_.-]）。 </summary>
    public required string OUCode { get; init; }
    /// <summary> 组织单元层级深度（透传 OU.Level，根=0）。 </summary>
    public int OULevel { get; init; }
    /// <summary> 组织单元显示名（透传 OU.Name，可含任意字符）。 </summary>
    public required string OUName { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static UserOrganizationUnitViewDto FromEntity(UserOrganizationUnitView entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new UserOrganizationUnitViewDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            OrganizationUnitId = entity.OrganizationUnitId,
            UserId = entity.UserId,
            OUPath = entity.OUPath,
            OUCode = entity.OUCode,
            OULevel = entity.OULevel,
            OUName = entity.OUName,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<UserOrganizationUnitView, UserOrganizationUnitViewDto>> SelectExpression => e => new UserOrganizationUnitViewDto
    {
        Id = e.Id,
        OrganizationUnitId = e.OrganizationUnitId,
        UserId = e.UserId,
        OUPath = e.OUPath,
        OUCode = e.OUCode,
        OULevel = e.OULevel,
        OUName = e.OUName,
    };
    #endregion

    UserOrganizationUnitView IDomainDto<UserOrganizationUnitView>.ApplyToEntity(UserOrganizationUnitView entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(OrganizationUnitId), d => d.OrganizationUnitId, (e, v) => e.OrganizationUnitId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(OUPath), d => d.OUPath, (e, v) => e.OUPath = v )
            .Map(nameof(OUCode), d => d.OUCode, (e, v) => e.OUCode = v )
            .Map(nameof(OULevel), d => d.OULevel, (e, v) => e.OULevel = v )
            .Map(nameof(OUName), d => d.OUName, (e, v) => e.OUName = v )
        ;
        return entity;
    }

    UserOrganizationUnitView IDomainDto<UserOrganizationUnitView>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(UserOrganizationUnitViewDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<UserOrganizationUnitView>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<UserOrganizationUnitView, UserOrganizationUnitViewDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class UserOrganizationUnitViewDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static UserOrganizationUnitViewDto ToDto(this UserOrganizationUnitView entity) => UserOrganizationUnitViewDto.FromEntity(entity);
}

