// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9e570da5cc641a950cc83750d2aff67adefce336489092ee7459e67ef498a5ea]
// 模型: AccessCodeEntity (TKWF.Ext.TrustCenter.AccessCodeEntity)
// 生成时间: 2026-10-10 09:46:25
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.TrustCenter;

// V4.10.24 (G10): 实体类级 XML Doc 移入手写实体类（[DomainGenerateCode] partial 声明）——
// 此处不再给 partial class 写 <summary>（旧占位"条件工厂（V4.9）..."会被 Roslyn 合并进
// symbol.GetDocumentationCommentXml()，遮蔽手写实体描述）。条件工厂说明挪至 Conditions 嵌套类上方。
partial class AccessCodeEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    /// <summary>
    /// 条件工厂（V4.9）。支持两种使用方式：
    /// <list type="bullet">
    /// <item><c>AccessCodeEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
    /// <item><c>AccessCodeEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
    /// </list>
    /// </summary>
    public static class Conditions
    {
        /// <summary>精确匹配：TKWFIXAccessCodeCodeHash（Unique 索引，必填参数）</summary>
        public static Expression<Func<AccessCodeEntity, bool>> ByTKWFIXAccessCodeCodeHash(string codeHash)
            => x => x.CodeHash == codeHash;

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<AccessCodeEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<AccessCodeEntity, bool>> All(params Expression<Func<AccessCodeEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<AccessCodeEntity, bool>> Any(params Expression<Func<AccessCodeEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>AccessCodeEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<AccessCodeEntity>
    {

        /// <summary>精确匹配：TKWFIXAccessCodeCodeHash（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByTKWFIXAccessCodeCodeHash(string codeHash)
            => (PredicateBuilder)Update(Conditions.ByTKWFIXAccessCodeCodeHash(codeHash));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<AccessCodeEntity> CreateBranch() => new PredicateBuilder();
}
}
