// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 4af7ae97b76e4c58d2fa81c9c8d65f914747ed59df27f8b86ebc4b069d804282]
// 模型: AuthAppEntity (TKWF.Ext.AuthSurface.AuthAppEntity)
// 生成时间: 2026-10-07 14:19:59
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.AuthSurface;

namespace TKWF.Ext.AuthSurface.DTOs;
/// <summary>应用目录实体（表 <c>AuthApp</c>）——"我的应用"聚合的 AppName 来源。  <para>背景：AuthCenter <c>AuthGrantEntity</c> 底座<b>无应用元数据</b>（仅 AppId 裸 id——explore 实证）；  独立目录表 = OAuth2 client 注册表语义（长期演进清晰），不动 AuthCenter（跨扩展零改）。</para>  <para>⚠️ 软引用语义：<see cref="AppId"/> 与 <c>AuthGrant.AppId</c> / <c>RedemptionCode.TargetAppId</c> 为字符串约定  （无 FK 约束）——删除前检查引用；建议 <c>SetEnabledAsync(false)</c> 软禁用而非物理删除（防 vm_UserApps 丢 AppName）。</para></summary>
public partial record AuthAppEntityDto : IDomainDto<AuthAppEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary>  </summary>
    public long Id { get; init; }
    /// <summary> 应用/产品 id——唯一；对齐 <c>AuthGrant.AppId</c> / <c>RedemptionCode.TargetAppId</c> 语义。 </summary>
    public required string AppId { get; init; }
    /// <summary> 应用名（"我的应用"列表展示字段）。 </summary>
    public required string AppName { get; init; }
    /// <summary> 图标 URL（string 非二进制——对齐 AuthAccount.Avatar 先例）。 </summary>
    public string? Icon { get; init; }
    /// <summary> 启用标记——false = 软禁用（应用不出现在"我的应用"聚合结果语义由门面保证）。 </summary>
    public bool IsEnabled { get; init; }
    /// <summary>  </summary>
    public DateTime CreateTime { get; init; }
    /// <summary>  </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static AuthAppEntityDto FromEntity(AuthAppEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new AuthAppEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            AppId = entity.AppId,
            AppName = entity.AppName,
            Icon = entity.Icon,
            IsEnabled = entity.IsEnabled,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<AuthAppEntity, AuthAppEntityDto>> SelectExpression => e => new AuthAppEntityDto
    {
        Id = e.Id,
        AppId = e.AppId,
        AppName = e.AppName,
        Icon = e.Icon,
        IsEnabled = e.IsEnabled,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    AuthAppEntity IDomainDto<AuthAppEntity>.ApplyToEntity(AuthAppEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(AppId), d => d.AppId, (e, v) => e.AppId = v )
            .Map(nameof(AppName), d => d.AppName, (e, v) => e.AppName = v )
            .Map(nameof(Icon), d => d.Icon, (e, v) => e.Icon = v )
            .Map(nameof(IsEnabled), d => d.IsEnabled, (e, v) => e.IsEnabled = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    AuthAppEntity IDomainDto<AuthAppEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(AuthAppEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<AuthAppEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<AuthAppEntity, AuthAppEntityDto>(scene, results)
                .MaxLength(nameof(AppId), 100, d => d.AppId)
                .MaxLength(nameof(AppName), 100, d => d.AppName)
                .MaxLength(nameof(Icon), 512, d => d.Icon)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class AuthAppEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static AuthAppEntityDto ToDto(this AuthAppEntity entity) => AuthAppEntityDto.FromEntity(entity);
}

