// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 5a78eed3d201f40763636fe5572d2c8db87f70aaa456869bdcdc263272c7d4b7]
// 模型: FeatureValueEntity (TKWF.Ext.FeatureManagement.FeatureValueEntity)
// 生成时间: 2026-09-14 08:05:57
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.FeatureManagement;

namespace TKWF.Ext.FeatureManagement.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>FeatureValueEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>FeatureValueEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record FeatureValueEntityDto : IDomainDto<FeatureValueEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> Feature 名（对应 FeatureDefinition.Name）。 </summary>
    public required string Name { get; init; }
    /// <summary> 值（字符串表示）。     <para>v0.3.0：<c>[MaxLength(512)]</c> → <c>[MaxLength(-1)]</c>（FreeSql 无界字符串约定——     SQLite=text/Pg=text/SqlServer=nvarchar(max)），容纳 JSON 复杂值；新装库 SyncTables 幂等建无界列；     存量库 VARCHAR(512) 加宽依赖 SyncTables 实现（若未自动 ALTER 需 DBA 手动变更，见使用指南）。     注：单纯移除 MaxLength 属性 FreeSql 默认映射 NVARCHAR(255)（仍受限）——须显式 <c>MaxLength(-1)</c>。</para> </summary>
    public string? Value { get; init; }
    /// <summary> Provider 层（Global/Tenant/Role/User）。 </summary>
    public required string ProviderName { get; init; }
    /// <summary> ProviderKey（Global=null；Tenant=TenantId；Role=角色名；User=UserId）。 </summary>
    public string? ProviderKey { get; init; }
    /// <summary> 描述（管理界面）。 </summary>
    public string? Description { get; init; }
    /// <summary> 是否对客户端可见（管理界面过滤）。 </summary>
    public bool IsVisibleToClients { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（UTC）。 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static FeatureValueEntityDto FromEntity(FeatureValueEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new FeatureValueEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Name = entity.Name,
            Value = entity.Value,
            ProviderName = entity.ProviderName,
            ProviderKey = entity.ProviderKey,
            Description = entity.Description,
            IsVisibleToClients = entity.IsVisibleToClients,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<FeatureValueEntity, FeatureValueEntityDto>> SelectExpression => e => new FeatureValueEntityDto
    {
        Id = e.Id,
        Name = e.Name,
        Value = e.Value,
        ProviderName = e.ProviderName,
        ProviderKey = e.ProviderKey,
        Description = e.Description,
        IsVisibleToClients = e.IsVisibleToClients,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    FeatureValueEntity IDomainDto<FeatureValueEntity>.ApplyToEntity(FeatureValueEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(Value), d => d.Value, (e, v) => e.Value = v )
            .Map(nameof(ProviderName), d => d.ProviderName, (e, v) => e.ProviderName = v )
            .Map(nameof(ProviderKey), d => d.ProviderKey, (e, v) => e.ProviderKey = v )
            .Map(nameof(Description), d => d.Description, (e, v) => e.Description = v )
            .Map(nameof(IsVisibleToClients), d => d.IsVisibleToClients, (e, v) => e.IsVisibleToClients = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    FeatureValueEntity IDomainDto<FeatureValueEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(FeatureValueEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<FeatureValueEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<FeatureValueEntity, FeatureValueEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class FeatureValueEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static FeatureValueEntityDto ToDto(this FeatureValueEntity entity) => FeatureValueEntityDto.FromEntity(entity);
}

