// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 02cb9376f5bfe1d2bda2013c5da0864b6f390beae855e5634ed32b15751c123d]
// 模型: BlobRecordEntity (TKWF.Ext.BlobStoring.BlobRecordEntity)
// 生成时间: 2026-09-14 08:05:49
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.BlobStoring;

namespace TKWF.Ext.BlobStoring.DTOs;
/// <summary>Blob 记录表实体——存储二进制大对象的元数据（名称、路径、内容类型、大小、标签、上传者等）。     <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>。     SG1 自动生成 <see cref="!:TKW.Framework.Domain.IDomainEntity"/> 部分与 DTO/DataService。</para>     <para>保留 BCL <c>[Table("BlobRecord")]</c>（<c>FreeSqlTableStructureSynchronizer</c> 靠它发现实体建表）；     列映射用 FreeSql <c>[Column]</c>（IsPrimary/IsIdentity/Position，全限定避免与 BCL Schema 特性名冲突）。</para></summary>
public partial record BlobRecordEntityDto : IDomainDto<BlobRecordEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> Blob 名称（业务键，如文件名）。 </summary>
    public required string Name { get; init; }
    /// <summary> 存储路径（相对 RootPath 的路径）。 </summary>
    public required string Path { get; init; }
    /// <summary> MIME 内容类型（如 image/png）。 </summary>
    public string? ContentType { get; init; }
    /// <summary> 文件大小（字节）。 </summary>
    public long Size { get; init; }
    /// <summary> 标签（JSON 数组字符串）。 </summary>
    public string? Tags { get; init; }
    /// <summary> 上传者名称。 </summary>
    public string? UploaderName { get; init; }
    /// <summary> 创建时间。 </summary>
    public required DateTimeOffset CreateTime { get; init; }
    /// <summary> 更新时间。 </summary>
    public required DateTimeOffset UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static BlobRecordEntityDto FromEntity(BlobRecordEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new BlobRecordEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Name = entity.Name,
            Path = entity.Path,
            ContentType = entity.ContentType,
            Size = entity.Size,
            Tags = entity.Tags,
            UploaderName = entity.UploaderName,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<BlobRecordEntity, BlobRecordEntityDto>> SelectExpression => e => new BlobRecordEntityDto
    {
        Id = e.Id,
        Name = e.Name,
        Path = e.Path,
        ContentType = e.ContentType,
        Size = e.Size,
        Tags = e.Tags,
        UploaderName = e.UploaderName,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    BlobRecordEntity IDomainDto<BlobRecordEntity>.ApplyToEntity(BlobRecordEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v )
            .Map(nameof(Path), d => d.Path, (e, v) => e.Path = v )
            .Map(nameof(ContentType), d => d.ContentType, (e, v) => e.ContentType = v )
            .Map(nameof(Size), d => d.Size, (e, v) => e.Size = v )
            .Map(nameof(Tags), d => d.Tags, (e, v) => e.Tags = v )
            .Map(nameof(UploaderName), d => d.UploaderName, (e, v) => e.UploaderName = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    BlobRecordEntity IDomainDto<BlobRecordEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(BlobRecordEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<BlobRecordEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<BlobRecordEntity, BlobRecordEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class BlobRecordEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static BlobRecordEntityDto ToDto(this BlobRecordEntity entity) => BlobRecordEntityDto.FromEntity(entity);
}

