// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: a32305a48541abeae198eb42af1594fe09de20139b602ba2a5b64fcac1b9924f]
// 模型: UserRoleEntity (TKWF.Ext.Identity.UserRoleEntity)
// 生成时间: 2026-09-14 08:06:01
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Identity;

namespace TKWF.Ext.Identity.DTOs;
/// <summary>条件工厂（V4.9）。支持两种使用方式：     <list type="bullet">     <item><c>UserRoleEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>     <item><c>UserRoleEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>     </list></summary>
public partial record UserRoleEntityDto : IDomainDto<UserRoleEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 用户 ID（<see cref="P:TKWF.Ext.Identity.UserEntity.Id"/>，索引）。 </summary>
    public long UserId { get; init; }
    /// <summary> 角色 ID（<see cref="P:TKWF.Ext.Identity.RoleEntity.Id"/>，索引）。 </summary>
    public long RoleId { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static UserRoleEntityDto FromEntity(UserRoleEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new UserRoleEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UserId = entity.UserId,
            RoleId = entity.RoleId,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<UserRoleEntity, UserRoleEntityDto>> SelectExpression => e => new UserRoleEntityDto
    {
        Id = e.Id,
        UserId = e.UserId,
        RoleId = e.RoleId,
    };
    #endregion

    UserRoleEntity IDomainDto<UserRoleEntity>.ApplyToEntity(UserRoleEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(RoleId), d => d.RoleId, (e, v) => e.RoleId = v )
        ;
        return entity;
    }

    UserRoleEntity IDomainDto<UserRoleEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(UserRoleEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<UserRoleEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<UserRoleEntity, UserRoleEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class UserRoleEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static UserRoleEntityDto ToDto(this UserRoleEntity entity) => UserRoleEntityDto.FromEntity(entity);
}

