// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9f5cc96b77a93da3fb73533e3e230052b7c2d11ab4d4537c266e8b191e222a47]
// 模型: ApprovalTaskEntity (TKWF.Ext.Approval.ApprovalTaskEntity)
// 生成时间: 2026-09-14 09:20:39
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.Approval;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>ApprovalTaskEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>ApprovalTaskEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class ApprovalTaskEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：IXApprovalTaskAssignee（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<ApprovalTaskEntity, bool>> ByIXApprovalTaskAssignee(ApprovalTaskStatus status, string approverUserId)
        {
            return x => x.Status == status &&
            x.ApproverUserId == approverUserId;
        }

        /// <summary>模糊搜索：ApproverUserId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<ApprovalTaskEntity, bool>> LikeApproverUserId(string? approverUserId = null)
        {
            if (string.IsNullOrEmpty(approverUserId)) return None;
            var val = approverUserId!;
            return x => x.ApproverUserId != null && x.ApproverUserId.Contains(val);
        }
        /// <summary>多值模糊搜索：IXApprovalTaskAssignee（按 ApproverUserId Or-链）</summary>
        public static Expression<Func<ApprovalTaskEntity, bool>> LikeIXApprovalTaskAssigneeKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<ApprovalTaskEntity>(x => x.ApproverUserId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：IXApprovalTaskAssignee（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<ApprovalTaskEntity, bool>> EqualIXApprovalTaskAssignee(string value)
        {
            return x => x.ApproverUserId == value;
        }
        /// <summary>组合条件：IXApprovalTaskInstance（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<ApprovalTaskEntity, bool>> ByIXApprovalTaskInstance(long instanceId)
        {
            return x => x.InstanceId == instanceId;
        }

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<ApprovalTaskEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<ApprovalTaskEntity, bool>> All(params Expression<Func<ApprovalTaskEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<ApprovalTaskEntity, bool>> Any(params Expression<Func<ApprovalTaskEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>ApprovalTaskEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<ApprovalTaskEntity>
    {

        /// <summary>组合条件：IXApprovalTaskAssignee（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXApprovalTaskAssignee(ApprovalTaskStatus status, string approverUserId)
            => (PredicateBuilder)Update(Conditions.ByIXApprovalTaskAssignee(status, approverUserId));

        /// <summary>模糊搜索：ApproverUserId（单个关键字）</summary>
        public PredicateBuilder LikeApproverUserId(string? approverUserId = null)
            => (PredicateBuilder)Update(Conditions.LikeApproverUserId(approverUserId));

        /// <summary>多值模糊搜索：IXApprovalTaskAssignee（按关键词 Or-链）</summary>
        public PredicateBuilder LikeIXApprovalTaskAssigneeKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeIXApprovalTaskAssigneeKeywords(keywords));

        /// <summary>跨属性精确匹配：IXApprovalTaskAssignee（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualIXApprovalTaskAssignee(string value)
            => (PredicateBuilder)Update(Conditions.EqualIXApprovalTaskAssignee(value));

        /// <summary>组合条件：IXApprovalTaskInstance（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXApprovalTaskInstance(long instanceId)
            => (PredicateBuilder)Update(Conditions.ByIXApprovalTaskInstance(instanceId));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<ApprovalTaskEntity> CreateBranch() => new PredicateBuilder();
}
}
