// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: bcc87beb477298211f750c4de48998bc4e9f6e47ea79c628189f8f8ebb830363]
// 模型: UserProfileEntity (TKWF.Ext.AuthCenter.UserProfileEntity)
// 生成时间: 2026-10-07 16:11:19
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Entity;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.AuthCenter;
using TKWF.Ext.AuthCenter.DTOs;
using TKW.Framework.Domain.Interfaces;
using System.ComponentModel;

namespace TKWF.Ext.AuthCenter;

/// <summary>
/// </summary>
 sealed partial class UserProfileEntityDataService : IGeneratedByxCodeGenCli
{
    #region [ 内部原子逻辑转发 (Internal Accessors) ]

    /// <summary> 转发基类受保护的 QueryForUser，供同程序集 Controller 组合查询 Entity </summary>
    /// <remarks>优先使用 EntityGetAsync / EntitySelectAsync 等异步安全方法，仅在需要组合复杂查询时使用此属性。</remarks>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal IQueryable<UserProfileEntity> Query => QueryForUser();

    /// <summary> 转发基类受保护的 InternalGetAsync </summary>
    internal Task<UserProfileEntity?> EntityGetAsync(Expression<Func<UserProfileEntity, bool>> predicate, CancellationToken ct = default) 
        => InternalGetAsync(predicate, ct);

    /// <summary> 转发基类受保护的 InternalSelectAsync </summary>
    internal Task<List<UserProfileEntity>> EntitySelectAsync(
        Expression<Func<UserProfileEntity, bool>>? predicate, 
        int skip = 0, int limit = 100, 
        Func<IQueryable<UserProfileEntity>, IQueryable<UserProfileEntity>>? orderBy = null, 
        CancellationToken ct = default)
        => InternalSelectAsync(predicate, skip, limit, orderBy, ct);


    // --- 仅非视图(可写)实体拥有的转发方法 ---

    /// <summary> 转发基类受保护的 InternalCreateAsync </summary>
    internal Task<UserProfileEntity> EntityCreateAsync(UserProfileEntity entity, CancellationToken ct = default)
        => InternalCreateAsync(entity, ct);

    /// <summary> 转发基类受保护的 InternalCreateBatchAsync (批量插入) </summary>
    internal Task<List<UserProfileEntity>> EntityCreateBatchAsync(IEnumerable<UserProfileEntity> entities, CancellationToken ct = default)
        => InternalCreateBatchAsync(entities, ct);

    /// <summary> 转发基类受保护的 InternalUpdateAsync（返回更新后的实体） </summary>
    internal Task<UserProfileEntity> EntityUpdateAsync(UserProfileEntity entity, CancellationToken ct = default)
        => InternalUpdateAsync(entity, ct);

    /// <summary> 转发基类受保护的 InternalUpdateBatchAsync (全字段批量更新) </summary>
    internal Task EntityUpdateBatchAsync(IEnumerable<UserProfileEntity> entities, CancellationToken ct = default)
        => InternalUpdateBatchAsync(entities, ct);

    /// <summary> 转发基类受保护的 InternalUpdateColumnsBatchAsync (指定列批量更新) </summary>
    internal Task<int> EntityUpdateColumnsBatchAsync<TColumns>(
        IEnumerable<UserProfileEntity> entities, 
        Expression<Func<UserProfileEntity, TColumns>> columns, 
        CancellationToken ct = default)
        => InternalUpdateColumnsBatchAsync(entities, columns, ct);

    /// <summary> 转发基类受保护的 InternalUpdateWhereAsync (条件原子更新——ADR89：单语句 WHERE 谓词更新 + 影响行数) </summary>
    internal Task<int> EntityUpdateWhereAsync<TColumns>(
        Expression<Func<UserProfileEntity, bool>> where, 
        Expression<Func<UserProfileEntity, TColumns>> setColumns, 
        CancellationToken ct = default)
        => InternalUpdateWhereAsync(where, setColumns, ct);

    /// <summary> 转发基类受保护的 InternalSoftDeleteAsync (软删除) </summary>
    internal Task<bool> EntitySoftDeleteAsync(long id, CancellationToken ct = default)
        => InternalSoftDeleteAsync(id, ct);

    /// <summary> 转发基类受保护的 InternalDeleteBatchAsync (批量删除) </summary>
    internal Task<int> EntityDeleteBatchAsync(IEnumerable<long> ids, CancellationToken ct = default)
        => InternalDeleteBatchAsync(ids, ct);
        
    #endregion
} // end service class