// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 64c9c5513d4a3c89364a494140c5d68da2272a2c2694db56585fb3a710f43940]
// 模型: DataImportRecordEntity (TKWF.Ext.DataPort.DataImportRecordEntity)
// 生成时间: 2026-09-14 08:05:54
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.DataPort;

namespace TKWF.Ext.DataPort.DTOs;
/// <summary>数据导入批次记录实体——记录每次导入的元数据（批次号/文件哈希/状态/统计/错误摘要）。     <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>。     SG1 自动生成 <see cref="!:TKW.Framework.Domain.IDomainEntity"/> 部分与 DTO/DataService。</para>     <para>保留 BCL <c>[Table("DataImportRecord")]</c>（<c>FreeSqlTableStructureSynchronizer</c> 靠它发现实体建表）；     列映射用 FreeSql <c>[Column]</c>（IsPrimary/IsIdentity/Position，全限定避免与 BCL Schema 特性名冲突）。</para>     <para>FileHash 唯一索引防重复导入（幂等检查入口）；BatchNo 供消费方按批次回滚。</para></summary>
public partial record DataImportRecordEntityDto : IDomainDto<DataImportRecordEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 批次号（GUID，消费方回滚入口）。 </summary>
    public required string BatchNo { get; init; }
    /// <summary> 文件哈希（SHA256，幂等检查——同文件二次导入拒绝）。 </summary>
    public required string FileHash { get; init; }
    /// <summary> 原始文件名。 </summary>
    public required string FileName { get; init; }
    /// <summary> Provider 名称（如 "miniexcel"）。 </summary>
    public required string ProviderName { get; init; }
    /// <summary> 导入状态（Processing/Succeeded/Failed/PartiallySucceeded）。 </summary>
    public required string Status { get; init; }
    /// <summary> 验证通过数（独立于批次持久化）。 </summary>
    public int SuccessCount { get; init; }
    /// <summary> 行级失败数。 </summary>
    public int FailedCount { get; init; }
    /// <summary> 批次级持久化失败数。 </summary>
    public int BatchFailureCount { get; init; }
    /// <summary> 开始时间（UTC）——由任务服务显式赋值（SQLite Provider 类型映射缺 DateTimeOffset，时间列统一用 DateTime）。 </summary>
    public DateTime StartTime { get; init; }
    /// <summary> 结束时间（UTC）——由任务服务显式赋值（SQLite Provider 类型映射缺 DateTimeOffset，时间列统一用 DateTime）。 </summary>
    public DateTime? EndTime { get; init; }
    /// <summary> 错误摘要（前 N 个失败消息拼接，便于快速排查）。 </summary>
    public string? ErrorSummary { get; init; }
    /// <summary> 创建人（CreatedUser.UserGuid，Oracle m6：CreatedBy 审计字段）。 </summary>
    public string? CreatedBy { get; init; }
    /// <summary> 创建时间（UTC）——由任务服务显式赋值（SQLite Provider 类型映射缺 DateTimeOffset，时间列统一用 DateTime）。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（UTC）——由任务服务显式赋值（SQLite Provider 类型映射缺 DateTimeOffset，时间列统一用 DateTime）。 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static DataImportRecordEntityDto FromEntity(DataImportRecordEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new DataImportRecordEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            BatchNo = entity.BatchNo,
            FileHash = entity.FileHash,
            FileName = entity.FileName,
            ProviderName = entity.ProviderName,
            Status = entity.Status,
            SuccessCount = entity.SuccessCount,
            FailedCount = entity.FailedCount,
            BatchFailureCount = entity.BatchFailureCount,
            StartTime = entity.StartTime,
            EndTime = entity.EndTime,
            ErrorSummary = entity.ErrorSummary,
            CreatedBy = entity.CreatedBy,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<DataImportRecordEntity, DataImportRecordEntityDto>> SelectExpression => e => new DataImportRecordEntityDto
    {
        Id = e.Id,
        BatchNo = e.BatchNo,
        FileHash = e.FileHash,
        FileName = e.FileName,
        ProviderName = e.ProviderName,
        Status = e.Status,
        SuccessCount = e.SuccessCount,
        FailedCount = e.FailedCount,
        BatchFailureCount = e.BatchFailureCount,
        StartTime = e.StartTime,
        EndTime = e.EndTime,
        ErrorSummary = e.ErrorSummary,
        CreatedBy = e.CreatedBy,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    DataImportRecordEntity IDomainDto<DataImportRecordEntity>.ApplyToEntity(DataImportRecordEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(BatchNo), d => d.BatchNo, (e, v) => e.BatchNo = v )
            .Map(nameof(FileHash), d => d.FileHash, (e, v) => e.FileHash = v )
            .Map(nameof(FileName), d => d.FileName, (e, v) => e.FileName = v )
            .Map(nameof(ProviderName), d => d.ProviderName, (e, v) => e.ProviderName = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(SuccessCount), d => d.SuccessCount, (e, v) => e.SuccessCount = v )
            .Map(nameof(FailedCount), d => d.FailedCount, (e, v) => e.FailedCount = v )
            .Map(nameof(BatchFailureCount), d => d.BatchFailureCount, (e, v) => e.BatchFailureCount = v )
            .Map(nameof(StartTime), d => d.StartTime, (e, v) => e.StartTime = v )
            .Map(nameof(EndTime), d => d.EndTime, (e, v) => e.EndTime = v )
            .Map(nameof(ErrorSummary), d => d.ErrorSummary, (e, v) => e.ErrorSummary = v )
            .Map(nameof(CreatedBy), d => d.CreatedBy, (e, v) => e.CreatedBy = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    DataImportRecordEntity IDomainDto<DataImportRecordEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(DataImportRecordEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<DataImportRecordEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<DataImportRecordEntity, DataImportRecordEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class DataImportRecordEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static DataImportRecordEntityDto ToDto(this DataImportRecordEntity entity) => DataImportRecordEntityDto.FromEntity(entity);
}

