// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: c492de2e6dfd509838fdc39b3419ed29da679a1bbf32844a131786a38a2e7a95]
// 模型: DataImportRecordEntity (TKWF.Ext.DataPort.DataImportRecordEntity)
// 生成时间: 2026-09-14 08:05:54
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.DataPort;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>DataImportRecordEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>DataImportRecordEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class DataImportRecordEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>精确匹配：IXDirBatchno（Unique 索引，必填参数）</summary>
        public static Expression<Func<DataImportRecordEntity, bool>> ByIXDirBatchno(string batchNo)
            => x => x.BatchNo == batchNo;

        /// <summary>精确匹配：IXDirFilehash（Unique 索引，必填参数）</summary>
        public static Expression<Func<DataImportRecordEntity, bool>> ByIXDirFilehash(string fileHash)
            => x => x.FileHash == fileHash;

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<DataImportRecordEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<DataImportRecordEntity, bool>> All(params Expression<Func<DataImportRecordEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<DataImportRecordEntity, bool>> Any(params Expression<Func<DataImportRecordEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>DataImportRecordEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<DataImportRecordEntity>
    {

        /// <summary>精确匹配：IXDirBatchno（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByIXDirBatchno(string batchNo)
            => (PredicateBuilder)Update(Conditions.ByIXDirBatchno(batchNo));

        /// <summary>精确匹配：IXDirFilehash（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByIXDirFilehash(string fileHash)
            => (PredicateBuilder)Update(Conditions.ByIXDirFilehash(fileHash));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<DataImportRecordEntity> CreateBranch() => new PredicateBuilder();
}
}
