// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 00a6d60ed0f4b4a32b1fd9136d37c1cb34d75aa9194d8ea81fcccf69212a59d7]
// 模型: AuthGrantEntity (TKWF.Ext.AuthCenter.AuthGrantEntity)
// 生成时间: 2026-10-06 12:04:11
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.AuthCenter;

namespace TKWF.Ext.AuthCenter.DTOs;
/// <summary>应用授权实体——OAuth2 authorization grant 语义（V0.8.0 `/grants` 端点数据底座 + B-口令兑换产品线写入点预留）。      <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>（不指定 UserType——ADR42 D4，供任意装配实例）。</para>      <para>语义：记录"用户授权某应用访问其数据的持久授权"（应用授权有效期 <see cref="ValidUntil"/>，跨会话），      与令牌生命周期（2h access / 30d refresh）正交；唯一约束 UX(UserId,AppId,Source) 防并发 exchange 产生重复 grant 行。</para></summary>
public partial record AuthGrantEntityDto : IDomainDto<AuthGrantEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 平台内部 id（JWT sub 同源——授权归属用户）。 </summary>
    public required string UserId { get; init; }
    /// <summary> 授权应用 id（/grants 查询维度）。 </summary>
    public required string AppId { get; init; }
    /// <summary> 逗号分隔授权范围（v0.8.0 login 源空串；⚠️ 已知局限——按单 scope 查询需 LIKE 无法走索引，     未来 scope 维度查询变热时 normalizate 为 AuthGrantScopeEntity(GrantId, Scope)，本迭代不过度设计）。 </summary>
    public required string Scopes { get; init; }
    /// <summary> 应用授权有效期（UTC；null = 持续至 Status 翻转为 Revoked——对齐 OAuth2 grant persist 语义，     非会话有效期；login 源默认 null；redeem 源未来按口令 valid_until 填值）。 </summary>
    public DateTime? ValidUntil { get; init; }
    /// <summary> 授权来源（AuthGrantSources 常量：login 登录授权 / redeem 口令兑换预留）。 </summary>
    public required string Source { get; init; }
    /// <summary> 授权状态（0 Active / 1 Revoked——管理吊销预留，本迭代仅 Active）。 </summary>
    public int Status { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（UTC）。 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static AuthGrantEntityDto FromEntity(AuthGrantEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new AuthGrantEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UserId = entity.UserId,
            AppId = entity.AppId,
            Scopes = entity.Scopes,
            ValidUntil = entity.ValidUntil,
            Source = entity.Source,
            Status = entity.Status,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<AuthGrantEntity, AuthGrantEntityDto>> SelectExpression => e => new AuthGrantEntityDto
    {
        Id = e.Id,
        UserId = e.UserId,
        AppId = e.AppId,
        Scopes = e.Scopes,
        ValidUntil = e.ValidUntil,
        Source = e.Source,
        Status = e.Status,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    AuthGrantEntity IDomainDto<AuthGrantEntity>.ApplyToEntity(AuthGrantEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(AppId), d => d.AppId, (e, v) => e.AppId = v )
            .Map(nameof(Scopes), d => d.Scopes, (e, v) => e.Scopes = v )
            .Map(nameof(ValidUntil), d => d.ValidUntil, (e, v) => e.ValidUntil = v )
            .Map(nameof(Source), d => d.Source, (e, v) => e.Source = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    AuthGrantEntity IDomainDto<AuthGrantEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(AuthGrantEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<AuthGrantEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<AuthGrantEntity, AuthGrantEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class AuthGrantEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static AuthGrantEntityDto ToDto(this AuthGrantEntity entity) => AuthGrantEntityDto.FromEntity(entity);
}

