// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: fe7460939f53a2b9020a0094ef39925e3f6de85626c2e5ff9b2b69562c9620b4]
// 模型: AuthRefreshTokenEntity (TKWF.Ext.AuthCenter.AuthRefreshTokenEntity)
// 生成时间: 2026-10-06 05:00:32
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.AuthCenter;

namespace TKWF.Ext.AuthCenter.DTOs;
/// <summary>刷新令牌实体——Refresh rotation（SHA256 落库，新旧不可复用 + TokenVersion 闭环）。      <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>（不指定 UserType——ADR42 D4）。</para>      <para>令牌明文不落库——仅存 SHA256 hex；刷新时校验 TokenVersion 匹配（不匹配 → 拒绝，闭环 DMP 缺口）。</para></summary>
public partial record AuthRefreshTokenEntityDto : IDomainDto<AuthRefreshTokenEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 对应 Access Token jti。 </summary>
    public required string Jti { get; init; }
    /// <summary> 平台内部 id（JWT sub 引用）。 </summary>
    public required string UserId { get; init; }
    /// <summary> 签发时认证方式：sms/wechat/password/redeem。 </summary>
    public required string AuthType { get; init; }
    /// <summary> Refresh Token SHA256 hex（不存明文）；唯一索引。 </summary>
    public required string TokenHash { get; init; }
    /// <summary> 签发时账号 TokenVersion——刷新时校验（不匹配 → 拒绝）。 </summary>
    public int TokenVersion { get; init; }
    /// <summary> 过期时间（UTC，默认 30d）。 </summary>
    public DateTime ExpiresAt { get; init; }
    /// <summary> 是否已撤销（rotation 消费后置 true）。 </summary>
    public bool IsRevoked { get; init; }
    /// <summary> 撤销时间（UTC）。 </summary>
    public DateTime? RevokedAt { get; init; }
    /// <summary> 签发设备信息（可选）。 </summary>
    public string? DeviceInfo { get; init; }
    /// <summary> 创建时间（UTC）；索引 (UserId, TokenVersion)。 </summary>
    public DateTime CreateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static AuthRefreshTokenEntityDto FromEntity(AuthRefreshTokenEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new AuthRefreshTokenEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Jti = entity.Jti,
            UserId = entity.UserId,
            AuthType = entity.AuthType,
            TokenHash = entity.TokenHash,
            TokenVersion = entity.TokenVersion,
            ExpiresAt = entity.ExpiresAt,
            IsRevoked = entity.IsRevoked,
            RevokedAt = entity.RevokedAt,
            DeviceInfo = entity.DeviceInfo,
            CreateTime = entity.CreateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<AuthRefreshTokenEntity, AuthRefreshTokenEntityDto>> SelectExpression => e => new AuthRefreshTokenEntityDto
    {
        Id = e.Id,
        Jti = e.Jti,
        UserId = e.UserId,
        AuthType = e.AuthType,
        TokenHash = e.TokenHash,
        TokenVersion = e.TokenVersion,
        ExpiresAt = e.ExpiresAt,
        IsRevoked = e.IsRevoked,
        RevokedAt = e.RevokedAt,
        DeviceInfo = e.DeviceInfo,
        CreateTime = e.CreateTime,
    };
    #endregion

    AuthRefreshTokenEntity IDomainDto<AuthRefreshTokenEntity>.ApplyToEntity(AuthRefreshTokenEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Jti), d => d.Jti, (e, v) => e.Jti = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(AuthType), d => d.AuthType, (e, v) => e.AuthType = v )
            .Map(nameof(TokenHash), d => d.TokenHash, (e, v) => e.TokenHash = v )
            .Map(nameof(TokenVersion), d => d.TokenVersion, (e, v) => e.TokenVersion = v )
            .Map(nameof(ExpiresAt), d => d.ExpiresAt, (e, v) => e.ExpiresAt = v )
            .Map(nameof(IsRevoked), d => d.IsRevoked, (e, v) => e.IsRevoked = v )
            .Map(nameof(RevokedAt), d => d.RevokedAt, (e, v) => e.RevokedAt = v )
            .Map(nameof(DeviceInfo), d => d.DeviceInfo, (e, v) => e.DeviceInfo = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
        ;
        return entity;
    }

    AuthRefreshTokenEntity IDomainDto<AuthRefreshTokenEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(AuthRefreshTokenEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<AuthRefreshTokenEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<AuthRefreshTokenEntity, AuthRefreshTokenEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class AuthRefreshTokenEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static AuthRefreshTokenEntityDto ToDto(this AuthRefreshTokenEntity entity) => AuthRefreshTokenEntityDto.FromEntity(entity);
}

