// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: d79b4fd798327e21c8b61989832a9c9045844178ba40e2f63cc38904d9fdd6b9]
// 模型: PasswordResetCodeEntity (TKWF.Ext.AuthCenter.PasswordResetCodeEntity)
// 生成时间: 2026-10-07 16:11:19
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.AuthCenter;

namespace TKWF.Ext.AuthCenter.DTOs;
/// <summary>密码重置码实体（V0.9.0 B.10/B.11——找回多通道自建链路落库底座）。      <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>（ADR42 D4，供任意装配实例）。</para>      <para>⚠️ 与 Account 扩展 <c>PasswordResetCodeEntity</c>（userName-keyed，表 <c>PasswordResetCode</c>）<b>同名不同命名空间</b>      （本类 <c>TKWF.Ext.AuthCenter</c> / 表 <c>TKWF_PasswordResetCode</c>）——ADR B.10 明确 AuthCenter 自建 UId-keyed 链路      （绑定 Account 契约按 userName 写 IdentityUser，与 AuthAccount UId/Phone 模型平行不互认），两实体零冲突。</para>      <para>CodeHash 单向散列（SHA256 hex——不存明文；对标 SmsRecord.CodeHash）；多通道字段 Channel=SMS/Email/OAuthTicket      （B.10 层级区分：验证码通道可达 / 扫码身份持有证明）；自带投递（B.11 修复 Account 侧 InitiateResetAsync 生成码不投递缺口）。</para>      <para>表名 <c>TKWF_PasswordResetCode</c>（ADR100——AuthCenter 表前缀批次）。</para></summary>
public partial record PasswordResetCodeEntityDto : IDomainDto<PasswordResetCodeEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 平台内部 id（AuthAccount.UId——UId-keyed，非 userName；找回目标账号）。 </summary>
    public required string UId { get; init; }
    /// <summary> 找回通道（SMS/Email/OAuthTicket——SmsScenes.Reset 语义 / Emailing 投递 / 扫码前置证明）。 </summary>
    public required string Channel { get; init; }
    /// <summary> 重置码散列（SHA256 hex——不存明文；对标 SmsRecord.CodeHash 单向散列）。 </summary>
    public required string CodeHash { get; init; }
    /// <summary> 过期时间（UTC——TTL 一次性；扫码通道对接 OAuthTicket 生命周期）。 </summary>
    public DateTime ExpireAt { get; init; }
    /// <summary> 是否已消费（单次消费防重放——兑现后置 true，重复提交拒绝）。 </summary>
    public bool IsConsumed { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static PasswordResetCodeEntityDto FromEntity(PasswordResetCodeEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new PasswordResetCodeEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            Channel = entity.Channel,
            CodeHash = entity.CodeHash,
            ExpireAt = entity.ExpireAt,
            IsConsumed = entity.IsConsumed,
            CreateTime = entity.CreateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<PasswordResetCodeEntity, PasswordResetCodeEntityDto>> SelectExpression => e => new PasswordResetCodeEntityDto
    {
        Id = e.Id,
        UId = e.UId,
        Channel = e.Channel,
        CodeHash = e.CodeHash,
        ExpireAt = e.ExpireAt,
        IsConsumed = e.IsConsumed,
        CreateTime = e.CreateTime,
    };
    #endregion

    PasswordResetCodeEntity IDomainDto<PasswordResetCodeEntity>.ApplyToEntity(PasswordResetCodeEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(Channel), d => d.Channel, (e, v) => e.Channel = v )
            .Map(nameof(CodeHash), d => d.CodeHash, (e, v) => e.CodeHash = v )
            .Map(nameof(ExpireAt), d => d.ExpireAt, (e, v) => e.ExpireAt = v )
            .Map(nameof(IsConsumed), d => d.IsConsumed, (e, v) => e.IsConsumed = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
        ;
        return entity;
    }

    PasswordResetCodeEntity IDomainDto<PasswordResetCodeEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(PasswordResetCodeEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<PasswordResetCodeEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<PasswordResetCodeEntity, PasswordResetCodeEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class PasswordResetCodeEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static PasswordResetCodeEntityDto ToDto(this PasswordResetCodeEntity entity) => PasswordResetCodeEntityDto.FromEntity(entity);
}

