// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9d9b2bbbcacc623094f7d061ffcf9851fe4a3712c19cd005dc6237471a10ef12]
// 模型: PlatformCredentialEntity (TKWF.Ext.AuthCenter.PlatformCredentialEntity)
// 生成时间: 2026-10-07 16:11:19
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.AuthCenter;

namespace TKWF.Ext.AuthCenter.DTOs;
/// <summary>第三方平台凭证实体——公众号/小程序/网站应用/移动应用凭证（AppSecret AES-GCM 加密存储）。      <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>（不指定 UserType——ADR42 D4）。</para>      <para>摒弃 DMP 纯 POCO 裸 FreeSql——SG1 化 + DataService 委托；加密在 DataService 边界（Service 层只见明文）。</para></summary>
public partial record PlatformCredentialEntityDto : IDomainDto<PlatformCredentialEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 平台：wechat/douyin/alipay。 </summary>
    public required string Platform { get; init; }
    /// <summary> 应用类型：公众号/小程序/网站应用/移动应用。 </summary>
    public required string AppType { get; init; }
    /// <summary> 应用 AppId。 </summary>
    public required string AppId { get; init; }
    /// <summary> 应用名称（可选）。 </summary>
    public string? AppName { get; init; }
    /// <summary> 是否启用（默认 true）。 </summary>
    public bool IsEnabled { get; init; }
    /// <summary> 创建时间（UTC）；唯一索引 (Platform, AppType, AppId)。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（UTC）。 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static PlatformCredentialEntityDto FromEntity(PlatformCredentialEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new PlatformCredentialEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Platform = entity.Platform,
            AppType = entity.AppType,
            AppId = entity.AppId,
            AppName = entity.AppName,
            IsEnabled = entity.IsEnabled,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<PlatformCredentialEntity, PlatformCredentialEntityDto>> SelectExpression => e => new PlatformCredentialEntityDto
    {
        Id = e.Id,
        Platform = e.Platform,
        AppType = e.AppType,
        AppId = e.AppId,
        AppName = e.AppName,
        IsEnabled = e.IsEnabled,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    PlatformCredentialEntity IDomainDto<PlatformCredentialEntity>.ApplyToEntity(PlatformCredentialEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Platform), d => d.Platform, (e, v) => e.Platform = v )
            .Map(nameof(AppType), d => d.AppType, (e, v) => e.AppType = v )
            .Map(nameof(AppId), d => d.AppId, (e, v) => e.AppId = v )
            .Map(nameof(AppName), d => d.AppName, (e, v) => e.AppName = v )
            .Map(nameof(IsEnabled), d => d.IsEnabled, (e, v) => e.IsEnabled = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    PlatformCredentialEntity IDomainDto<PlatformCredentialEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(PlatformCredentialEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<PlatformCredentialEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<PlatformCredentialEntity, PlatformCredentialEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class PlatformCredentialEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static PlatformCredentialEntityDto ToDto(this PlatformCredentialEntity entity) => PlatformCredentialEntityDto.FromEntity(entity);
}

