// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 1c9f1c426dcaedc15415f8a5bacf412891be850fcaf6227f05ab896c0c132be3]
// 模型: PlatformAccountMapEntity (TKWF.Ext.AuthCenter.PlatformAccountMapEntity)
// 生成时间: 2026-10-07 16:11:19
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.AuthCenter;

namespace TKWF.Ext.AuthCenter.DTOs;
/// <summary>跨系统映射实体——平台内部 id ↔ 业务 app + 业务本地 id + UnionId（统一 DMP 双机制：映射表/外键）。      <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>（不指定 UserType——ADR42 D4）。</para>      <para>DMP V4.0 管理员走映射表、会员走外键——Ext 以本表统一承载；DMP 迁移时会员映射迁入本表（需求 §6 约束 1）。</para></summary>
public partial record PlatformAccountMapEntityDto : IDomainDto<PlatformAccountMapEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 平台内部 id（Ext 账号表 AuthAccount.UId）。 </summary>
    public required string PlatformAccountId { get; init; }
    /// <summary> 业务应用 id。 </summary>
    public required string BusinessAppId { get; init; }
    /// <summary> 业务系统本地 id。 </summary>
    public required string BusinessLocalId { get; init; }
    /// <summary> 微信 unionid（可选，跨应用关联）。 </summary>
    public string? UnionId { get; init; }
    /// <summary> channel 实例 id（SSO 联邦映射，如微信公众号 id；可空——既有业务 app 映射行不填，ADR-SSO Oracle P1-3）。 </summary>
    public string? ChannelId { get; init; }
    /// <summary> 渠道身份标识（SSO 联邦映射，如商户 openid2；可空——既有行 NULL 放行）。 </summary>
    public string? ExternalUserId { get; init; }
    /// <summary> 创建时间（UTC）；唯一索引 (PlatformAccountId, BusinessAppId, BusinessLocalId)。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（UTC）。 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static PlatformAccountMapEntityDto FromEntity(PlatformAccountMapEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new PlatformAccountMapEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            PlatformAccountId = entity.PlatformAccountId,
            BusinessAppId = entity.BusinessAppId,
            BusinessLocalId = entity.BusinessLocalId,
            UnionId = entity.UnionId,
            ChannelId = entity.ChannelId,
            ExternalUserId = entity.ExternalUserId,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<PlatformAccountMapEntity, PlatformAccountMapEntityDto>> SelectExpression => e => new PlatformAccountMapEntityDto
    {
        Id = e.Id,
        PlatformAccountId = e.PlatformAccountId,
        BusinessAppId = e.BusinessAppId,
        BusinessLocalId = e.BusinessLocalId,
        UnionId = e.UnionId,
        ChannelId = e.ChannelId,
        ExternalUserId = e.ExternalUserId,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    PlatformAccountMapEntity IDomainDto<PlatformAccountMapEntity>.ApplyToEntity(PlatformAccountMapEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(PlatformAccountId), d => d.PlatformAccountId, (e, v) => e.PlatformAccountId = v )
            .Map(nameof(BusinessAppId), d => d.BusinessAppId, (e, v) => e.BusinessAppId = v )
            .Map(nameof(BusinessLocalId), d => d.BusinessLocalId, (e, v) => e.BusinessLocalId = v )
            .Map(nameof(UnionId), d => d.UnionId, (e, v) => e.UnionId = v )
            .Map(nameof(ChannelId), d => d.ChannelId, (e, v) => e.ChannelId = v )
            .Map(nameof(ExternalUserId), d => d.ExternalUserId, (e, v) => e.ExternalUserId = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    PlatformAccountMapEntity IDomainDto<PlatformAccountMapEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(PlatformAccountMapEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<PlatformAccountMapEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<PlatformAccountMapEntity, PlatformAccountMapEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class PlatformAccountMapEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static PlatformAccountMapEntityDto ToDto(this PlatformAccountMapEntity entity) => PlatformAccountMapEntityDto.FromEntity(entity);
}

