// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9cdae4400eee8bbcd9d80217ee1eac4addeb6065a6b642e02aafc82ec07dd999]
// 模型: UserProfileEntity (TKWF.Ext.AuthCenter.UserProfileEntity)
// 生成时间: 2026-10-07 16:11:19
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.AuthCenter;

namespace TKWF.Ext.AuthCenter.DTOs;
/// <summary>用户档案实体——认证中心基础档案 1:1（V0.9.0 凭据/档案表级分离 A.1：Nickname/Avatar/Birthday/Gender/Email）。      <para>SG1 化：声明式实体——<c>partial</c> + <c>[DomainGenerateCode]</c>（不指定 UserType——ADR42 D4，供任意装配实例）。</para>      <para>红线（数据访问）：档案读写经 SG1 生成 <see cref="UserProfileEntityDataService"/>——零 IFreeSql/IEntityDAC 直注入。</para>      <para>字段语义（ADR A.5/A.6/A.7）：<b>Phone 双角色</b>——凭据角色归 <see cref="AuthAccountEntity.Phone"/>（登录锚点），      联系方式角色由业务层自决（框架不提供"复制登录号"默认操作）；<b>Email</b> 联系方式列（不启用登录凭据——A.6 fail-closed      默认关闭，Email 找回通道与 Email 登录凭据是两件事可独立启用）；<b>Gender</b> 宽松自由文本（max 32，无枚举约束——A.7）。</para>      <para>表名 <c>TKWF_UserProfile</c>（ADR100——AuthCenter 表前缀批次）。</para></summary>
public partial record UserProfileEntityDto : IDomainDto<UserProfileEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 平台内部 id（1:1 关联 <see cref="P:TKWF.Ext.AuthCenter.AuthAccountEntity.UId"/>——档案仅此标识，无独立删除生命周期）。 </summary>
    public required string UId { get; init; }
    /// <summary> 昵称（V0.9.0 从 AuthAccount 迁入；微信授权拉取）。 </summary>
    public string? Nickname { get; init; }
    /// <summary> 头像 URL（string 非二进制——DMP 实践确认；V0.9.0 从 AuthAccount 迁入）。 </summary>
    public string? Avatar { get; init; }
    /// <summary> 生日（可空——档案宽松可选）。 </summary>
    public DateTime? Birthday { get; init; }
    /// <summary> 性别——宽松自由文本（可空 max 32，无枚举约束——B.7 "108 种性别"场景，框架不枚举业务分类）。 </summary>
    public string? Gender { get; init; }
    /// <summary> 邮箱——联系方式角色（A.5；可空。V0.9.0 不作为登录凭据——A.6 Email 可选凭据扩展点 fail-closed 默认关）。 </summary>
    public string? Email { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 更新时间（UTC）。 </summary>
    public DateTime UpdateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static UserProfileEntityDto FromEntity(UserProfileEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new UserProfileEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            UId = entity.UId,
            Nickname = entity.Nickname,
            Avatar = entity.Avatar,
            Birthday = entity.Birthday,
            Gender = entity.Gender,
            Email = entity.Email,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<UserProfileEntity, UserProfileEntityDto>> SelectExpression => e => new UserProfileEntityDto
    {
        Id = e.Id,
        UId = e.UId,
        Nickname = e.Nickname,
        Avatar = e.Avatar,
        Birthday = e.Birthday,
        Gender = e.Gender,
        Email = e.Email,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };
    #endregion

    UserProfileEntity IDomainDto<UserProfileEntity>.ApplyToEntity(UserProfileEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(UId), d => d.UId, (e, v) => e.UId = v )
            .Map(nameof(Nickname), d => d.Nickname, (e, v) => e.Nickname = v )
            .Map(nameof(Avatar), d => d.Avatar, (e, v) => e.Avatar = v )
            .Map(nameof(Birthday), d => d.Birthday, (e, v) => e.Birthday = v )
            .Map(nameof(Gender), d => d.Gender, (e, v) => e.Gender = v )
            .Map(nameof(Email), d => d.Email, (e, v) => e.Email = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v )
        ;
        return entity;
    }

    UserProfileEntity IDomainDto<UserProfileEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(UserProfileEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<UserProfileEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<UserProfileEntity, UserProfileEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class UserProfileEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static UserProfileEntityDto ToDto(this UserProfileEntity entity) => UserProfileEntityDto.FromEntity(entity);
}

