// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 510b2ff40280a06333b63e72a49e74d4a0a0d16a18a7b2d37606336356f4ee17]
// 模型: RateLimitCounterEntity (TKWF.Ext.RateLimiting.RateLimitCounterEntity)
// 生成时间: 2026-10-07 18:43:47
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Entity;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.RateLimiting;
using TKWF.Ext.RateLimiting.DTOs;
using TKW.Framework.Domain.Interfaces;
using System.ComponentModel;

namespace TKWF.Ext.RateLimiting;

/// <summary>
/// </summary>
 sealed partial class RateLimitCounterEntityDataService : IGeneratedByxCodeGenCli
{
    #region [ 内部原子逻辑转发 (Internal Accessors) ]

    /// <summary> 转发基类受保护的 QueryForUser，供同程序集 Controller 组合查询 Entity </summary>
    /// <remarks>优先使用 EntityGetAsync / EntitySelectAsync 等异步安全方法，仅在需要组合复杂查询时使用此属性。</remarks>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal IQueryable<RateLimitCounterEntity> Query => QueryForUser();

    /// <summary> 转发基类受保护的 InternalGetAsync </summary>
    internal Task<RateLimitCounterEntity?> EntityGetAsync(Expression<Func<RateLimitCounterEntity, bool>> predicate, CancellationToken ct = default) 
        => InternalGetAsync(predicate, ct);

    /// <summary> 转发基类受保护的 InternalSelectAsync </summary>
    internal Task<List<RateLimitCounterEntity>> EntitySelectAsync(
        Expression<Func<RateLimitCounterEntity, bool>>? predicate, 
        int skip = 0, int limit = 100, 
        Func<IQueryable<RateLimitCounterEntity>, IQueryable<RateLimitCounterEntity>>? orderBy = null, 
        CancellationToken ct = default)
        => InternalSelectAsync(predicate, skip, limit, orderBy, ct);


    // --- 仅非视图(可写)实体拥有的转发方法 ---

    /// <summary> 转发基类受保护的 InternalCreateAsync </summary>
    internal Task<RateLimitCounterEntity> EntityCreateAsync(RateLimitCounterEntity entity, CancellationToken ct = default)
        => InternalCreateAsync(entity, ct);

    /// <summary> 转发基类受保护的 InternalCreateBatchAsync (批量插入) </summary>
    internal Task<List<RateLimitCounterEntity>> EntityCreateBatchAsync(IEnumerable<RateLimitCounterEntity> entities, CancellationToken ct = default)
        => InternalCreateBatchAsync(entities, ct);

    /// <summary> 转发基类受保护的 InternalUpdateAsync（返回更新后的实体） </summary>
    internal Task<RateLimitCounterEntity> EntityUpdateAsync(RateLimitCounterEntity entity, CancellationToken ct = default)
        => InternalUpdateAsync(entity, ct);

    /// <summary> 转发基类受保护的 InternalUpdateBatchAsync (全字段批量更新) </summary>
    internal Task EntityUpdateBatchAsync(IEnumerable<RateLimitCounterEntity> entities, CancellationToken ct = default)
        => InternalUpdateBatchAsync(entities, ct);

    /// <summary> 转发基类受保护的 InternalUpdateColumnsBatchAsync (指定列批量更新) </summary>
    internal Task<int> EntityUpdateColumnsBatchAsync<TColumns>(
        IEnumerable<RateLimitCounterEntity> entities, 
        Expression<Func<RateLimitCounterEntity, TColumns>> columns, 
        CancellationToken ct = default)
        => InternalUpdateColumnsBatchAsync(entities, columns, ct);

    /// <summary> 转发基类受保护的 InternalUpdateWhereAsync (条件原子更新——ADR89：单语句 WHERE 谓词更新 + 影响行数) </summary>
    internal Task<int> EntityUpdateWhereAsync<TColumns>(
        Expression<Func<RateLimitCounterEntity, bool>> where, 
        Expression<Func<RateLimitCounterEntity, TColumns>> setColumns, 
        CancellationToken ct = default)
        => InternalUpdateWhereAsync(where, setColumns, ct);

    /// <summary> 转发基类受保护的 InternalSoftDeleteAsync (软删除) </summary>
    internal Task<bool> EntitySoftDeleteAsync(long id, CancellationToken ct = default)
        => InternalSoftDeleteAsync(id, ct);

    /// <summary> 转发基类受保护的 InternalDeleteBatchAsync (批量删除) </summary>
    internal Task<int> EntityDeleteBatchAsync(IEnumerable<long> ids, CancellationToken ct = default)
        => InternalDeleteBatchAsync(ids, ct);
        
    #endregion
} // end service class