// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: b90e0cf045986ec915e21f0a48229dc68dbf8ee9ea08f241562c3f783a0429cf]
// 模型: ApprovalAppendEntity (TKWF.Ext.Approval.ApprovalAppendEntity)
// 生成时间: 2026-09-14 09:20:39
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Approval;

namespace TKWF.Ext.Approval.DTOs;
/// <summary>加签记录实体——审批运行时当前审批人动态追加审批人（钉钉步骤内模型）。     <para>每加签人一行（Participate/Notify 均记录）；Participate 额外创建审批任务，Notify 仅记录 + 事件。     索引 UX_aa_instance_user（InstanceId+UserId，非唯一——同实例可多次加签同一人不同步骤）。</para></summary>
public partial record ApprovalAppendEntityDto : IDomainDto<ApprovalAppendEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 关联审批实例 ID。 </summary>
    public long InstanceId { get; init; }
    /// <summary> 关联任务 ID（当前步骤触发加签的任务）。 </summary>
    public long TaskId { get; init; }
    /// <summary> 步骤序号（加签发生在当前步骤）。 </summary>
    public int StepIndex { get; init; }
    /// <summary> 加签人用户 ID。 </summary>
    public required string UserId { get; init; }
    /// <summary> 操作人（当前审批人——触发加签的用户 ID）。 </summary>
    public required string OperatedByUserId { get; init; }
    /// <summary> 加签类型（Before/After——v0.2.0 行为一致，固定记录 After）。 </summary>
    public required ApprovalAppendType AppendType { get; init; }
    /// <summary> 加签模式（Participate 参与审批 / Notify 仅通知）。 </summary>
    public required ApprovalAppendMode AppendMode { get; init; }
    /// <summary> 加签理由（可选）。 </summary>
    public string? Remark { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static ApprovalAppendEntityDto FromEntity(ApprovalAppendEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new ApprovalAppendEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            InstanceId = entity.InstanceId,
            TaskId = entity.TaskId,
            StepIndex = entity.StepIndex,
            UserId = entity.UserId,
            OperatedByUserId = entity.OperatedByUserId,
            AppendType = entity.AppendType,
            AppendMode = entity.AppendMode,
            Remark = entity.Remark,
            CreateTime = entity.CreateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<ApprovalAppendEntity, ApprovalAppendEntityDto>> SelectExpression => e => new ApprovalAppendEntityDto
    {
        Id = e.Id,
        InstanceId = e.InstanceId,
        TaskId = e.TaskId,
        StepIndex = e.StepIndex,
        UserId = e.UserId,
        OperatedByUserId = e.OperatedByUserId,
        AppendType = e.AppendType,
        AppendMode = e.AppendMode,
        Remark = e.Remark,
        CreateTime = e.CreateTime,
    };
    #endregion

    ApprovalAppendEntity IDomainDto<ApprovalAppendEntity>.ApplyToEntity(ApprovalAppendEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(InstanceId), d => d.InstanceId, (e, v) => e.InstanceId = v )
            .Map(nameof(TaskId), d => d.TaskId, (e, v) => e.TaskId = v )
            .Map(nameof(StepIndex), d => d.StepIndex, (e, v) => e.StepIndex = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(OperatedByUserId), d => d.OperatedByUserId, (e, v) => e.OperatedByUserId = v )
            .Map(nameof(AppendType), d => d.AppendType, (e, v) => e.AppendType = v )
            .Map(nameof(AppendMode), d => d.AppendMode, (e, v) => e.AppendMode = v )
            .Map(nameof(Remark), d => d.Remark, (e, v) => e.Remark = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
        ;
        return entity;
    }

    ApprovalAppendEntity IDomainDto<ApprovalAppendEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(ApprovalAppendEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<ApprovalAppendEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<ApprovalAppendEntity, ApprovalAppendEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class ApprovalAppendEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static ApprovalAppendEntityDto ToDto(this ApprovalAppendEntity entity) => ApprovalAppendEntityDto.FromEntity(entity);
}

