// <auto-generated>
// 手动创建（对齐 xCodeGen 生成格式）
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Approval;

namespace TKWF.Ext.Approval.DTOs;

public partial record ApprovalAppendEntityDto : IDomainDto<ApprovalAppendEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    public long Id { get; init; }
    public long InstanceId { get; init; }
    public long TaskId { get; init; }
    public int StepIndex { get; init; }
    public required string UserId { get; init; }
    public required string OperatedByUserId { get; init; }
    public ApprovalAppendType AppendType { get; init; }
    public ApprovalAppendMode AppendMode { get; init; }
    public string? Remark { get; init; }
    public DateTime CreateTime { get; init; }

    public static ApprovalAppendEntityDto FromEntity(ApprovalAppendEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new ApprovalAppendEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            InstanceId = entity.InstanceId,
            TaskId = entity.TaskId,
            StepIndex = entity.StepIndex,
            UserId = entity.UserId,
            OperatedByUserId = entity.OperatedByUserId,
            AppendType = entity.AppendType,
            AppendMode = entity.AppendMode,
            Remark = entity.Remark,
            CreateTime = entity.CreateTime,
        };
    }

    public static Expression<Func<ApprovalAppendEntity, ApprovalAppendEntityDto>> SelectExpression => e => new ApprovalAppendEntityDto
    {
        Id = e.Id,
        InstanceId = e.InstanceId,
        TaskId = e.TaskId,
        StepIndex = e.StepIndex,
        UserId = e.UserId,
        OperatedByUserId = e.OperatedByUserId,
        AppendType = e.AppendType,
        AppendMode = e.AppendMode,
        Remark = e.Remark,
        CreateTime = e.CreateTime,
    };

    ApprovalAppendEntity IDomainDto<ApprovalAppendEntity>.ApplyToEntity(ApprovalAppendEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(InstanceId), d => d.InstanceId, (e, v) => e.InstanceId = v)
            .Map(nameof(TaskId), d => d.TaskId, (e, v) => e.TaskId = v)
            .Map(nameof(StepIndex), d => d.StepIndex, (e, v) => e.StepIndex = v)
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v)
            .Map(nameof(OperatedByUserId), d => d.OperatedByUserId, (e, v) => e.OperatedByUserId = v)
            .Map(nameof(AppendType), d => d.AppendType, (e, v) => e.AppendType = v)
            .Map(nameof(AppendMode), d => d.AppendMode, (e, v) => e.AppendMode = v)
            .Map(nameof(Remark), d => d.Remark, (e, v) => e.Remark = v)
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v)
        ;
        return entity;
    }

    ApprovalAppendEntity IDomainDto<ApprovalAppendEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(ApprovalAppendEntityDto)}.");
    }

    void IDomainDto<ApprovalAppendEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<ApprovalAppendEntity, ApprovalAppendEntityDto>(scene, results);
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

public static class ApprovalAppendEntityDtoExtensions
{
    public static ApprovalAppendEntityDto ToDto(this ApprovalAppendEntity entity) => ApprovalAppendEntityDto.FromEntity(entity);
}
