// <auto-generated>
// 手动创建（对齐 xCodeGen 生成格式，xCodeGen 配置待后续统一添加）
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Approval;

namespace TKWF.Ext.Approval.DTOs;

public partial record ApprovalFlowEntityDto : IDomainDto<ApprovalFlowEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    public long Id { get; init; }
    public required string Code { get; init; }
    public required string Name { get; init; }
    public string? Description { get; init; }
    public required string StepsJson { get; init; }
    public bool IsEnabled { get; init; }
    public DateTime CreateTime { get; init; }
    public DateTime UpdateTime { get; init; }

    public static ApprovalFlowEntityDto FromEntity(ApprovalFlowEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new ApprovalFlowEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            Code = entity.Code,
            Name = entity.Name,
            Description = entity.Description,
            StepsJson = entity.StepsJson,
            IsEnabled = entity.IsEnabled,
            CreateTime = entity.CreateTime,
            UpdateTime = entity.UpdateTime,
        };
    }

    public static Expression<Func<ApprovalFlowEntity, ApprovalFlowEntityDto>> SelectExpression => e => new ApprovalFlowEntityDto
    {
        Id = e.Id,
        Code = e.Code,
        Name = e.Name,
        Description = e.Description,
        StepsJson = e.StepsJson,
        IsEnabled = e.IsEnabled,
        CreateTime = e.CreateTime,
        UpdateTime = e.UpdateTime,
    };

    ApprovalFlowEntity IDomainDto<ApprovalFlowEntity>.ApplyToEntity(ApprovalFlowEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(Code), d => d.Code, (e, v) => e.Code = v)
            .Map(nameof(Name), d => d.Name, (e, v) => e.Name = v)
            .Map(nameof(Description), d => d.Description, (e, v) => e.Description = v)
            .Map(nameof(StepsJson), d => d.StepsJson, (e, v) => e.StepsJson = v)
            .Map(nameof(IsEnabled), d => d.IsEnabled, (e, v) => e.IsEnabled = v)
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v)
            .Map(nameof(UpdateTime), d => d.UpdateTime, (e, v) => e.UpdateTime = v)
        ;
        return entity;
    }

    ApprovalFlowEntity IDomainDto<ApprovalFlowEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(ApprovalFlowEntityDto)}.");
    }

    void IDomainDto<ApprovalFlowEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<ApprovalFlowEntity, ApprovalFlowEntityDto>(scene, results);
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

public static class ApprovalFlowEntityDtoExtensions
{
    public static ApprovalFlowEntityDto ToDto(this ApprovalFlowEntity entity) => ApprovalFlowEntityDto.FromEntity(entity);
}
