// <auto-generated>
// 手动创建（对齐 xCodeGen 生成格式）
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Approval;

namespace TKWF.Ext.Approval.DTOs;

public partial record ApprovalInstanceEntityDto : IDomainDto<ApprovalInstanceEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    public long Id { get; init; }
    public long FlowId { get; init; }
    public required string FlowCode { get; init; }
    public required string BusinessType { get; init; }
    public required string BusinessId { get; init; }
    public ApprovalInstanceStatus Status { get; init; }
    public bool IsActive { get; init; }
    public int CurrentStepIndex { get; init; }
    public required string Submitter { get; init; }
    public DateTime? SubmittedAt { get; init; }
    public DateTime? ApprovedAt { get; init; }
    public DateTime? RejectedAt { get; init; }
    public string? Reason { get; init; }
    public string? BusinessDataJson { get; init; }
    public string? CorrelationId { get; init; }
    public DateTime CreateTime { get; init; }

    public static ApprovalInstanceEntityDto FromEntity(ApprovalInstanceEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new ApprovalInstanceEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            FlowId = entity.FlowId,
            FlowCode = entity.FlowCode,
            BusinessType = entity.BusinessType,
            BusinessId = entity.BusinessId,
            Status = entity.Status,
            IsActive = entity.IsActive,
            CurrentStepIndex = entity.CurrentStepIndex,
            Submitter = entity.Submitter,
            SubmittedAt = entity.SubmittedAt,
            ApprovedAt = entity.ApprovedAt,
            RejectedAt = entity.RejectedAt,
            Reason = entity.Reason,
            BusinessDataJson = entity.BusinessDataJson,
            CorrelationId = entity.CorrelationId,
            CreateTime = entity.CreateTime,
        };
    }

    public static Expression<Func<ApprovalInstanceEntity, ApprovalInstanceEntityDto>> SelectExpression => e => new ApprovalInstanceEntityDto
    {
        Id = e.Id,
        FlowId = e.FlowId,
        FlowCode = e.FlowCode,
        BusinessType = e.BusinessType,
        BusinessId = e.BusinessId,
        Status = e.Status,
        IsActive = e.IsActive,
        CurrentStepIndex = e.CurrentStepIndex,
        Submitter = e.Submitter,
        SubmittedAt = e.SubmittedAt,
        ApprovedAt = e.ApprovedAt,
        RejectedAt = e.RejectedAt,
        Reason = e.Reason,
        BusinessDataJson = e.BusinessDataJson,
        CorrelationId = e.CorrelationId,
        CreateTime = e.CreateTime,
    };

    ApprovalInstanceEntity IDomainDto<ApprovalInstanceEntity>.ApplyToEntity(ApprovalInstanceEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(FlowId), d => d.FlowId, (e, v) => e.FlowId = v)
            .Map(nameof(FlowCode), d => d.FlowCode, (e, v) => e.FlowCode = v)
            .Map(nameof(BusinessType), d => d.BusinessType, (e, v) => e.BusinessType = v)
            .Map(nameof(BusinessId), d => d.BusinessId, (e, v) => e.BusinessId = v)
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v)
            .Map(nameof(IsActive), d => d.IsActive, (e, v) => e.IsActive = v)
            .Map(nameof(CurrentStepIndex), d => d.CurrentStepIndex, (e, v) => e.CurrentStepIndex = v)
            .Map(nameof(Submitter), d => d.Submitter, (e, v) => e.Submitter = v)
            .Map(nameof(SubmittedAt), d => d.SubmittedAt, (e, v) => e.SubmittedAt = v)
            .Map(nameof(ApprovedAt), d => d.ApprovedAt, (e, v) => e.ApprovedAt = v)
            .Map(nameof(RejectedAt), d => d.RejectedAt, (e, v) => e.RejectedAt = v)
            .Map(nameof(Reason), d => d.Reason, (e, v) => e.Reason = v)
            .Map(nameof(BusinessDataJson), d => d.BusinessDataJson, (e, v) => e.BusinessDataJson = v)
            .Map(nameof(CorrelationId), d => d.CorrelationId, (e, v) => e.CorrelationId = v)
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v)
        ;
        return entity;
    }

    ApprovalInstanceEntity IDomainDto<ApprovalInstanceEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(ApprovalInstanceEntityDto)}.");
    }

    void IDomainDto<ApprovalInstanceEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<ApprovalInstanceEntity, ApprovalInstanceEntityDto>(scene, results);
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

public static class ApprovalInstanceEntityDtoExtensions
{
    public static ApprovalInstanceEntityDto ToDto(this ApprovalInstanceEntity entity) => ApprovalInstanceEntityDto.FromEntity(entity);
}
