// <auto-generated>
// 手动创建（对齐 xCodeGen 生成格式）
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Approval;

namespace TKWF.Ext.Approval.DTOs;

public partial record ApprovalTaskEntityDto : IDomainDto<ApprovalTaskEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    public long Id { get; init; }
    public long InstanceId { get; init; }
    public int StepIndex { get; init; }
    public required string StepName { get; init; }
    public ApprovalApproverType ApproverType { get; init; }
    public required string ApproverValue { get; init; }
    public string? ApproverUserId { get; init; }
    public ApprovalTaskStatus Status { get; init; }
    public DateTime? ApprovedAt { get; init; }
    public string? ApprovedBy { get; init; }
    public string? Comment { get; init; }
    public string? TransferredTo { get; init; }
    public DateTime CreateTime { get; init; }
    public ApprovalDelegationState DelegationState { get; init; }
    public string? OriginalAssigneeId { get; init; }
    public string? DelegatedToUserId { get; init; }
    public DateTime? DelegatedAt { get; init; }
    public DateTime? TimeoutAt { get; init; }
    public ApprovalTimeoutAction? TimeoutAction { get; init; }
    public string? TimeoutTransferToUserId { get; init; }
    public int? TimeoutJumpToStepIndex { get; init; }
    public bool TimeoutProcessed { get; init; }

    public static ApprovalTaskEntityDto FromEntity(ApprovalTaskEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new ApprovalTaskEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            InstanceId = entity.InstanceId,
            StepIndex = entity.StepIndex,
            StepName = entity.StepName,
            ApproverType = entity.ApproverType,
            ApproverValue = entity.ApproverValue,
            ApproverUserId = entity.ApproverUserId,
            Status = entity.Status,
            ApprovedAt = entity.ApprovedAt,
            ApprovedBy = entity.ApprovedBy,
            Comment = entity.Comment,
            TransferredTo = entity.TransferredTo,
            CreateTime = entity.CreateTime,
            DelegationState = entity.DelegationState,
            OriginalAssigneeId = entity.OriginalAssigneeId,
            DelegatedToUserId = entity.DelegatedToUserId,
            DelegatedAt = entity.DelegatedAt,
            TimeoutAt = entity.TimeoutAt,
            TimeoutAction = entity.TimeoutAction,
            TimeoutTransferToUserId = entity.TimeoutTransferToUserId,
            TimeoutJumpToStepIndex = entity.TimeoutJumpToStepIndex,
            TimeoutProcessed = entity.TimeoutProcessed,
        };
    }

    public static Expression<Func<ApprovalTaskEntity, ApprovalTaskEntityDto>> SelectExpression => e => new ApprovalTaskEntityDto
    {
        Id = e.Id,
        InstanceId = e.InstanceId,
        StepIndex = e.StepIndex,
        StepName = e.StepName,
        ApproverType = e.ApproverType,
        ApproverValue = e.ApproverValue,
        ApproverUserId = e.ApproverUserId,
        Status = e.Status,
        ApprovedAt = e.ApprovedAt,
        ApprovedBy = e.ApprovedBy,
        Comment = e.Comment,
        TransferredTo = e.TransferredTo,
        CreateTime = e.CreateTime,
        DelegationState = e.DelegationState,
        OriginalAssigneeId = e.OriginalAssigneeId,
        DelegatedToUserId = e.DelegatedToUserId,
        DelegatedAt = e.DelegatedAt,
        TimeoutAt = e.TimeoutAt,
        TimeoutAction = e.TimeoutAction,
        TimeoutTransferToUserId = e.TimeoutTransferToUserId,
        TimeoutJumpToStepIndex = e.TimeoutJumpToStepIndex,
        TimeoutProcessed = e.TimeoutProcessed,
    };

    ApprovalTaskEntity IDomainDto<ApprovalTaskEntity>.ApplyToEntity(ApprovalTaskEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(InstanceId), d => d.InstanceId, (e, v) => e.InstanceId = v)
            .Map(nameof(StepIndex), d => d.StepIndex, (e, v) => e.StepIndex = v)
            .Map(nameof(StepName), d => d.StepName, (e, v) => e.StepName = v)
            .Map(nameof(ApproverType), d => d.ApproverType, (e, v) => e.ApproverType = v)
            .Map(nameof(ApproverValue), d => d.ApproverValue, (e, v) => e.ApproverValue = v)
            .Map(nameof(ApproverUserId), d => d.ApproverUserId, (e, v) => e.ApproverUserId = v)
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v)
            .Map(nameof(ApprovedAt), d => d.ApprovedAt, (e, v) => e.ApprovedAt = v)
            .Map(nameof(ApprovedBy), d => d.ApprovedBy, (e, v) => e.ApprovedBy = v)
            .Map(nameof(Comment), d => d.Comment, (e, v) => e.Comment = v)
            .Map(nameof(TransferredTo), d => d.TransferredTo, (e, v) => e.TransferredTo = v)
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v)
            .Map(nameof(DelegationState), d => d.DelegationState, (e, v) => e.DelegationState = v)
            .Map(nameof(OriginalAssigneeId), d => d.OriginalAssigneeId, (e, v) => e.OriginalAssigneeId = v)
            .Map(nameof(DelegatedToUserId), d => d.DelegatedToUserId, (e, v) => e.DelegatedToUserId = v)
            .Map(nameof(DelegatedAt), d => d.DelegatedAt, (e, v) => e.DelegatedAt = v)
            .Map(nameof(TimeoutAt), d => d.TimeoutAt, (e, v) => e.TimeoutAt = v)
            .Map(nameof(TimeoutAction), d => d.TimeoutAction, (e, v) => e.TimeoutAction = v)
            .Map(nameof(TimeoutTransferToUserId), d => d.TimeoutTransferToUserId, (e, v) => e.TimeoutTransferToUserId = v)
            .Map(nameof(TimeoutJumpToStepIndex), d => d.TimeoutJumpToStepIndex, (e, v) => e.TimeoutJumpToStepIndex = v)
            .Map(nameof(TimeoutProcessed), d => d.TimeoutProcessed, (e, v) => e.TimeoutProcessed = v)
        ;
        return entity;
    }

    ApprovalTaskEntity IDomainDto<ApprovalTaskEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(ApprovalTaskEntityDto)}.");
    }

    void IDomainDto<ApprovalTaskEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<ApprovalTaskEntity, ApprovalTaskEntityDto>(scene, results);
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

public static class ApprovalTaskEntityDtoExtensions
{
    public static ApprovalTaskEntityDto ToDto(this ApprovalTaskEntity entity) => ApprovalTaskEntityDto.FromEntity(entity);
}
