// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9e36e736002ec4dbc130ea6d946237248ba25be6235b9e73cb881cad2431c3e8]
// 模型: ApprovalCCEntity (TKWF.Ext.Approval.ApprovalCCEntity)
// 生成时间: 2026-09-14 09:20:39
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Approval;

namespace TKWF.Ext.Approval.DTOs;
/// <summary>抄送记录实体——审批发起/完成时通知相关人（不参与审批）。     <para>StartAsync 带 ccUserIds / AddCCAsync 记录；实例提交/终态时发布事件，投递组装消费方 Notifications。     索引 IX_ac_instance（InstanceId，非唯一）。</para></summary>
public partial record ApprovalCCEntityDto : IDomainDto<ApprovalCCEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 关联审批实例 ID。 </summary>
    public long InstanceId { get; init; }
    /// <summary> 抄送人用户 ID。 </summary>
    public required string UserId { get; init; }
    /// <summary> 抄送位置（Start/Finish/StartFinish）。 </summary>
    public required ApprovalCCPosition Position { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static ApprovalCCEntityDto FromEntity(ApprovalCCEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new ApprovalCCEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            InstanceId = entity.InstanceId,
            UserId = entity.UserId,
            Position = entity.Position,
            CreateTime = entity.CreateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<ApprovalCCEntity, ApprovalCCEntityDto>> SelectExpression => e => new ApprovalCCEntityDto
    {
        Id = e.Id,
        InstanceId = e.InstanceId,
        UserId = e.UserId,
        Position = e.Position,
        CreateTime = e.CreateTime,
    };
    #endregion

    ApprovalCCEntity IDomainDto<ApprovalCCEntity>.ApplyToEntity(ApprovalCCEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(InstanceId), d => d.InstanceId, (e, v) => e.InstanceId = v )
            .Map(nameof(UserId), d => d.UserId, (e, v) => e.UserId = v )
            .Map(nameof(Position), d => d.Position, (e, v) => e.Position = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
        ;
        return entity;
    }

    ApprovalCCEntity IDomainDto<ApprovalCCEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(ApprovalCCEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<ApprovalCCEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<ApprovalCCEntity, ApprovalCCEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class ApprovalCCEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static ApprovalCCEntityDto ToDto(this ApprovalCCEntity entity) => ApprovalCCEntityDto.FromEntity(entity);
}

