// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: a9d659ec9496ee030d166062df296d6971b97d593e19658266640bb2e87c0039]
// 模型: ApprovalTaskEntity (TKWF.Ext.Approval.ApprovalTaskEntity)
// 生成时间: 2026-09-14 09:20:39
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.Approval;

namespace TKWF.Ext.Approval.DTOs;
/// <summary>审批任务实体——步骤级待办（审批/驳回/转交载体）。     <para>每步骤根据审批人解析结果建一条任务（User 直接建一条 / Role 解析多人建多条）；     ApproverUserId 为解析结果快照（P1-4），避免 Role 模式重复查询。</para></summary>
public partial record ApprovalTaskEntityDto : IDomainDto<ApprovalTaskEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 关联审批实例 ID。 </summary>
    public long InstanceId { get; init; }
    /// <summary> 步骤序号（从 0 开始）。 </summary>
    public int StepIndex { get; init; }
    /// <summary> 步骤显示名（快照——如"部门经理""财务"）。 </summary>
    public required string StepName { get; init; }
    /// <summary> 审批人类型（User/Role）。 </summary>
    public required ApprovalApproverType ApproverType { get; init; }
    /// <summary> 审批人值（User=用户 ID，Role=角色名）。 </summary>
    public required string ApproverValue { get; init; }
    /// <summary> 审批人用户 ID（解析结果快照 P1-4）——Role 模式下为解析后的实际用户 ID。     <para>C1 安全校验：ApproveAsync/RejectAsync/TransferAsync 校验 approverUserId==task.ApproverUserId。</para> </summary>
    public string? ApproverUserId { get; init; }
    /// <summary> 任务状态（<see cref="T:TKWF.Ext.Approval.ApprovalTaskStatus"/>）。 </summary>
    public required ApprovalTaskStatus Status { get; init; }
    /// <summary> 审批通过时间。 </summary>
    public DateTime? ApprovedAt { get; init; }
    /// <summary> 审批通过人（用户 ID）。 </summary>
    public string? ApprovedBy { get; init; }
    /// <summary> 审批意见（可选）。 </summary>
    public string? Comment { get; init; }
    /// <summary> 转交给谁（转交后写入——原任务 Transferred 终态）。 </summary>
    public string? TransferredTo { get; init; }
    /// <summary> 创建时间（UTC）。 </summary>
    public DateTime CreateTime { get; init; }
    /// <summary> 委派状态（None/Pending/Resolved，默认 None）。 </summary>
    public required ApprovalDelegationState DelegationState { get; init; }
    /// <summary> 原审批人 ID（委派时记录——Resolve 后 ApproverUserId 回写此值）。 </summary>
    public string? OriginalAssigneeId { get; init; }
    /// <summary> 委派目标用户 ID（委派人成为当前处理人）。 </summary>
    public string? DelegatedToUserId { get; init; }
    /// <summary> 委派时间（UTC，DelegateTaskAsync 写入）。 </summary>
    public DateTime? DelegatedAt { get; init; }
    /// <summary> 超时时间点（任务创建时 = CreateTime + step.TimeoutMinutes；null=不超时）。 </summary>
    public DateTime? TimeoutAt { get; init; }
    /// <summary> 步骤超时动作快照（动作执行用；仅 TimeoutAt 非空时快照）。 </summary>
    public ApprovalTimeoutAction? TimeoutAction { get; init; }
    /// <summary> Transfer 动作目标用户快照（仅 TimeoutAt 非空时快照）。 </summary>
    public string? TimeoutTransferToUserId { get; init; }
    /// <summary> Jump 动作目标步骤序号快照（仅 TimeoutAt 非空时快照）。 </summary>
    public int? TimeoutJumpToStepIndex { get; init; }
    /// <summary> 超时已处理（扫描即占位防重复执行，P3——默认 false）。 </summary>
    public bool TimeoutProcessed { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static ApprovalTaskEntityDto FromEntity(ApprovalTaskEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new ApprovalTaskEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            InstanceId = entity.InstanceId,
            StepIndex = entity.StepIndex,
            StepName = entity.StepName,
            ApproverType = entity.ApproverType,
            ApproverValue = entity.ApproverValue,
            ApproverUserId = entity.ApproverUserId,
            Status = entity.Status,
            ApprovedAt = entity.ApprovedAt,
            ApprovedBy = entity.ApprovedBy,
            Comment = entity.Comment,
            TransferredTo = entity.TransferredTo,
            CreateTime = entity.CreateTime,
            DelegationState = entity.DelegationState,
            OriginalAssigneeId = entity.OriginalAssigneeId,
            DelegatedToUserId = entity.DelegatedToUserId,
            DelegatedAt = entity.DelegatedAt,
            TimeoutAt = entity.TimeoutAt,
            TimeoutAction = entity.TimeoutAction,
            TimeoutTransferToUserId = entity.TimeoutTransferToUserId,
            TimeoutJumpToStepIndex = entity.TimeoutJumpToStepIndex,
            TimeoutProcessed = entity.TimeoutProcessed,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<ApprovalTaskEntity, ApprovalTaskEntityDto>> SelectExpression => e => new ApprovalTaskEntityDto
    {
        Id = e.Id,
        InstanceId = e.InstanceId,
        StepIndex = e.StepIndex,
        StepName = e.StepName,
        ApproverType = e.ApproverType,
        ApproverValue = e.ApproverValue,
        ApproverUserId = e.ApproverUserId,
        Status = e.Status,
        ApprovedAt = e.ApprovedAt,
        ApprovedBy = e.ApprovedBy,
        Comment = e.Comment,
        TransferredTo = e.TransferredTo,
        CreateTime = e.CreateTime,
        DelegationState = e.DelegationState,
        OriginalAssigneeId = e.OriginalAssigneeId,
        DelegatedToUserId = e.DelegatedToUserId,
        DelegatedAt = e.DelegatedAt,
        TimeoutAt = e.TimeoutAt,
        TimeoutAction = e.TimeoutAction,
        TimeoutTransferToUserId = e.TimeoutTransferToUserId,
        TimeoutJumpToStepIndex = e.TimeoutJumpToStepIndex,
        TimeoutProcessed = e.TimeoutProcessed,
    };
    #endregion

    ApprovalTaskEntity IDomainDto<ApprovalTaskEntity>.ApplyToEntity(ApprovalTaskEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(InstanceId), d => d.InstanceId, (e, v) => e.InstanceId = v )
            .Map(nameof(StepIndex), d => d.StepIndex, (e, v) => e.StepIndex = v )
            .Map(nameof(StepName), d => d.StepName, (e, v) => e.StepName = v )
            .Map(nameof(ApproverType), d => d.ApproverType, (e, v) => e.ApproverType = v )
            .Map(nameof(ApproverValue), d => d.ApproverValue, (e, v) => e.ApproverValue = v )
            .Map(nameof(ApproverUserId), d => d.ApproverUserId, (e, v) => e.ApproverUserId = v )
            .Map(nameof(Status), d => d.Status, (e, v) => e.Status = v )
            .Map(nameof(ApprovedAt), d => d.ApprovedAt, (e, v) => e.ApprovedAt = v )
            .Map(nameof(ApprovedBy), d => d.ApprovedBy, (e, v) => e.ApprovedBy = v )
            .Map(nameof(Comment), d => d.Comment, (e, v) => e.Comment = v )
            .Map(nameof(TransferredTo), d => d.TransferredTo, (e, v) => e.TransferredTo = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
            .Map(nameof(DelegationState), d => d.DelegationState, (e, v) => e.DelegationState = v )
            .Map(nameof(OriginalAssigneeId), d => d.OriginalAssigneeId, (e, v) => e.OriginalAssigneeId = v )
            .Map(nameof(DelegatedToUserId), d => d.DelegatedToUserId, (e, v) => e.DelegatedToUserId = v )
            .Map(nameof(DelegatedAt), d => d.DelegatedAt, (e, v) => e.DelegatedAt = v )
            .Map(nameof(TimeoutAt), d => d.TimeoutAt, (e, v) => e.TimeoutAt = v )
            .Map(nameof(TimeoutAction), d => d.TimeoutAction, (e, v) => e.TimeoutAction = v )
            .Map(nameof(TimeoutTransferToUserId), d => d.TimeoutTransferToUserId, (e, v) => e.TimeoutTransferToUserId = v )
            .Map(nameof(TimeoutJumpToStepIndex), d => d.TimeoutJumpToStepIndex, (e, v) => e.TimeoutJumpToStepIndex = v )
            .Map(nameof(TimeoutProcessed), d => d.TimeoutProcessed, (e, v) => e.TimeoutProcessed = v )
        ;
        return entity;
    }

    ApprovalTaskEntity IDomainDto<ApprovalTaskEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(ApprovalTaskEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<ApprovalTaskEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<ApprovalTaskEntity, ApprovalTaskEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class ApprovalTaskEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static ApprovalTaskEntityDto ToDto(this ApprovalTaskEntity entity) => ApprovalTaskEntityDto.FromEntity(entity);
}

