// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 517c24acdb70f8bdd943ea7a7de4cd33b0742f11e9983b737ff237a63532d570]
// 模型: UserNotificationEntity (TKWF.Ext.Notifications.UserNotificationEntity)
// 生成时间: 2026-09-12 00:30:07
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.Notifications;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>UserNotificationEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>UserNotificationEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class UserNotificationEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>组合条件：IXUserNotificationNotificationId（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<UserNotificationEntity, bool>> ByIXUserNotificationNotificationId(long notificationId)
        {
            return x => x.NotificationId == notificationId;
        }

        /// <summary>组合条件：IXUserNotificationUserState（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<UserNotificationEntity, bool>> ByIXUserNotificationUserState(long userId, int state)
        {
            return x => x.UserId == userId &&
            x.State == state;
        }

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<UserNotificationEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<UserNotificationEntity, bool>> All(params Expression<Func<UserNotificationEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<UserNotificationEntity, bool>> Any(params Expression<Func<UserNotificationEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>UserNotificationEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<UserNotificationEntity>
    {

        /// <summary>组合条件：IXUserNotificationNotificationId（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXUserNotificationNotificationId(long notificationId)
            => (PredicateBuilder)Update(Conditions.ByIXUserNotificationNotificationId(notificationId));

        /// <summary>组合条件：IXUserNotificationUserState（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXUserNotificationUserState(long userId, int state)
            => (PredicateBuilder)Update(Conditions.ByIXUserNotificationUserState(userId, state));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<UserNotificationEntity> CreateBranch() => new PredicateBuilder();
}
}
