// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: b0a6a87b470ca831dc6fe46e776ea9ec907eb8f69c558985d043c09610e21c24]
// 模型: OrganizationUnitUserEntity (TKWF.Ext.OrganizationUnit.OrganizationUnitUserEntity)
// 生成时间: 2026-09-14 08:06:04
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.OrganizationUnit;

/// <summary>
/// 条件工厂（V4.9）。支持两种使用方式：
/// <list type="bullet">
/// <item><c>OrganizationUnitUserEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
/// <item><c>OrganizationUnitUserEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
/// </list>
/// </summary>
partial class OrganizationUnitUserEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    public static class Conditions
    {
        /// <summary>精确匹配：UXOrganizationUnitUserUserOU（Unique 索引，必填参数）</summary>
        public static Expression<Func<OrganizationUnitUserEntity, bool>> ByUXOrganizationUnitUserUserOU(long organizationUnitId, string userId)
            => x => x.OrganizationUnitId == organizationUnitId && x.UserId == userId;

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<OrganizationUnitUserEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<OrganizationUnitUserEntity, bool>> All(params Expression<Func<OrganizationUnitUserEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<OrganizationUnitUserEntity, bool>> Any(params Expression<Func<OrganizationUnitUserEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>OrganizationUnitUserEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<OrganizationUnitUserEntity>
    {

        /// <summary>精确匹配：UXOrganizationUnitUserUserOU（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByUXOrganizationUnitUserUserOU(long organizationUnitId, string userId)
            => (PredicateBuilder)Update(Conditions.ByUXOrganizationUnitUserUserOU(organizationUnitId, userId));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<OrganizationUnitUserEntity> CreateBranch() => new PredicateBuilder();
}
}
