// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 9681ba4f399c071370bfe00e5b2720c07252a70d20eff750614ceba6d0db159e]
// 模型: JobExecutionEntity (TKWF.Ext.BackgroundJobs.JobExecutionEntity)
// 生成时间: 2026-09-14 08:05:47
// </auto-generated>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TKW.Framework;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Domain.Interfaces;
using TKW.Framework.Domain.Exceptions;
using TKW.Framework.Domain.xCodeGen;
using TKWF.Ext.BackgroundJobs;

namespace TKWF.Ext.BackgroundJobs.DTOs;
/// <summary>作业执行历史实体（V0.1.0）——每次执行一行，记录耗时/重试/异常归档。</summary>
public partial record JobExecutionEntityDto : IDomainDto<JobExecutionEntity>
{
    [System.Text.Json.Serialization.JsonIgnore]
    public bool IsFromPersistentSource { get; set; }

    #region 属性定义
    /// <summary> 主键（自增）。 </summary>
    public long Id { get; init; }
    /// <summary> 调度器 JobId（弱关联透传，不跨模块引用实体）。 </summary>
    public required string JobId { get; init; }
    /// <summary> 作业类型（AssemblyQualifiedName）。 </summary>
    public required string JobType { get; init; }
    /// <summary> 调度器 Provider（builtin|hangfire|quartz）。 </summary>
    public required string Provider { get; init; }
    /// <summary> 是否成功。 </summary>
    public bool IsSuccess { get; init; }
    /// <summary> 是否被取消（OperationCanceledException）。 </summary>
    public bool IsCancelled { get; init; }
    /// <summary> 第几次执行尝试（内置重试 1-based；Hangfire/Quartz=1）。 </summary>
    public int RetryAttempt { get; init; }
    /// <summary> 执行耗时（毫秒）。 </summary>
    public long DurationMs { get; init; }
    /// <summary> 执行开始时间（UTC）。 </summary>
    public DateTime StartedAtUtc { get; init; }
    /// <summary> 执行完成时间（UTC）。 </summary>
    public DateTime CompletedAtUtc { get; init; }
    /// <summary> 异常归档（ex.ToString() 纯文本，对齐契约 Error——P1-1）。 </summary>
    public string? ErrorText { get; init; }
    /// <summary> 租户 Id（透传记录，依赖 TKWF 框架已有机制）。 </summary>
    public long? TenantId { get; init; }
    /// <summary> 创建时间（UTC——SQLite 可靠，Oracle P1-1）。 </summary>
    public DateTime CreateTime { get; init; }
    #endregion

    #region [ 静态工厂 ]
    /// <summary> 从实体转换为 DTO </summary>
    public static JobExecutionEntityDto FromEntity(JobExecutionEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);
        return new JobExecutionEntityDto
        {
            IsFromPersistentSource = entity.IsFromPersistentSource,
            Id = entity.Id,
            JobId = entity.JobId,
            JobType = entity.JobType,
            Provider = entity.Provider,
            IsSuccess = entity.IsSuccess,
            IsCancelled = entity.IsCancelled,
            RetryAttempt = entity.RetryAttempt,
            DurationMs = entity.DurationMs,
            StartedAtUtc = entity.StartedAtUtc,
            CompletedAtUtc = entity.CompletedAtUtc,
            ErrorText = entity.ErrorText,
            TenantId = entity.TenantId,
            CreateTime = entity.CreateTime,
        };
    }

    /// <summary>
    /// 查询投影表达式（供 DataService 无投影重载使用，保留 SQL 字段裁剪）。
    /// 必须是纯 MemberInit 表达式（new DTO { ... }）——FromEntity 是方法调用，FreeSql 无法翻译成 SQL；
    /// 且不得包含 IsFromPersistentSource（非业务列），由框架在取数后统一置位。
    /// </summary>
    public static Expression<Func<JobExecutionEntity, JobExecutionEntityDto>> SelectExpression => e => new JobExecutionEntityDto
    {
        Id = e.Id,
        JobId = e.JobId,
        JobType = e.JobType,
        Provider = e.Provider,
        IsSuccess = e.IsSuccess,
        IsCancelled = e.IsCancelled,
        RetryAttempt = e.RetryAttempt,
        DurationMs = e.DurationMs,
        StartedAtUtc = e.StartedAtUtc,
        CompletedAtUtc = e.CompletedAtUtc,
        ErrorText = e.ErrorText,
        TenantId = e.TenantId,
        CreateTime = e.CreateTime,
    };
    #endregion

    JobExecutionEntity IDomainDto<JobExecutionEntity>.ApplyToEntity(JobExecutionEntity entity, EnumSceneFlags scene)
    {
        ArgumentNullException.ThrowIfNull(entity);
        this.CreateMapper(entity, scene)
            .Map(nameof(JobId), d => d.JobId, (e, v) => e.JobId = v )
            .Map(nameof(JobType), d => d.JobType, (e, v) => e.JobType = v )
            .Map(nameof(Provider), d => d.Provider, (e, v) => e.Provider = v )
            .Map(nameof(IsSuccess), d => d.IsSuccess, (e, v) => e.IsSuccess = v )
            .Map(nameof(IsCancelled), d => d.IsCancelled, (e, v) => e.IsCancelled = v )
            .Map(nameof(RetryAttempt), d => d.RetryAttempt, (e, v) => e.RetryAttempt = v )
            .Map(nameof(DurationMs), d => d.DurationMs, (e, v) => e.DurationMs = v )
            .Map(nameof(StartedAtUtc), d => d.StartedAtUtc, (e, v) => e.StartedAtUtc = v )
            .Map(nameof(CompletedAtUtc), d => d.CompletedAtUtc, (e, v) => e.CompletedAtUtc = v )
            .Map(nameof(ErrorText), d => d.ErrorText, (e, v) => e.ErrorText = v )
            .Map(nameof(TenantId), d => d.TenantId, (e, v) => e.TenantId = v )
            .Map(nameof(CreateTime), d => d.CreateTime, (e, v) => e.CreateTime = v )
        ;
        return entity;
    }

    JobExecutionEntity IDomainDto<JobExecutionEntity>.ToEntity(EnumSceneFlags scene)
    {
        throw new NotSupportedException($"ToEntity not implemented for {nameof(JobExecutionEntityDto)}. Create entity manually or override in DTO extension file.");
    }

    void IDomainDto<JobExecutionEntity>.ValidateData(EnumSceneFlags scene)
    {
        if (IsFromPersistentSource && (scene & EnumSceneFlags.ForceValidate) == 0) return;
        
        var results = ValidateDataCore(scene).ToList();
        OnCustomValidate(scene, results);
        if (results.Any()) throw new ValidationResultsException(results);
    }

    protected IEnumerable<ValidationResult> ValidateDataCore(EnumSceneFlags scene)
    {
        var results = new List<ValidationResult>();
        this.CreateDtoValidator<JobExecutionEntity, JobExecutionEntityDto>(scene, results)
        ;
        return results;
    }

    partial void OnCustomValidate(EnumSceneFlags scene, List<ValidationResult> results);

    /// <summary>代码生成器标识</summary>
    public const string Generator = "xCodeGen:Dto.cshtml";
    public const string GeneratorVersion = "4.9";
}

/// <summary>Entity 转 DTO 扩展方法</summary>
public static class JobExecutionEntityDtoExtensions
{
    /// <summary> 将 Entity 转换为 DTO </summary>
    public static JobExecutionEntityDto ToDto(this JobExecutionEntity entity) => JobExecutionEntityDto.FromEntity(entity);
}

