// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 38461edb2dda5a93395a3b767ac6abf65ee3117000ef4abcff8f2b6c2231df72]
// 模型: AuthRefreshTokenEntity (TKWF.Ext.AuthCenter.AuthRefreshTokenEntity)
// 生成时间: 2026-10-06 05:00:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.AuthCenter;

// V4.10.24 (G10): 实体类级 XML Doc 移入手写实体类（[DomainGenerateCode] partial 声明）——
// 此处不再给 partial class 写 <summary>（旧占位"条件工厂（V4.9）..."会被 Roslyn 合并进
// symbol.GetDocumentationCommentXml()，遮蔽手写实体描述）。条件工厂说明挪至 Conditions 嵌套类上方。
partial class AuthRefreshTokenEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    /// <summary>
    /// 条件工厂（V4.9）。支持两种使用方式：
    /// <list type="bullet">
    /// <item><c>AuthRefreshTokenEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
    /// <item><c>AuthRefreshTokenEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
    /// </list>
    /// </summary>
    public static class Conditions
    {
        /// <summary>组合条件：IXAuthRefreshTokenUserVersion（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<AuthRefreshTokenEntity, bool>> ByIXAuthRefreshTokenUserVersion(int tokenVersion, string userId)
        {
            return x => x.TokenVersion == tokenVersion &&
            x.UserId == userId;
        }

        /// <summary>模糊搜索：UserId（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<AuthRefreshTokenEntity, bool>> LikeUserId(string? userId = null)
        {
            if (string.IsNullOrEmpty(userId)) return None;
            var val = userId!;
            return x => x.UserId.Contains(val);
        }
        /// <summary>多值模糊搜索：IXAuthRefreshTokenUserVersion（按 UserId Or-链）</summary>
        public static Expression<Func<AuthRefreshTokenEntity, bool>> LikeIXAuthRefreshTokenUserVersionKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<AuthRefreshTokenEntity>(x => x.UserId, keywords) ?? None;
        }
        /// <summary>跨属性精确匹配：IXAuthRefreshTokenUserVersion（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<AuthRefreshTokenEntity, bool>> EqualIXAuthRefreshTokenUserVersion(string value)
        {
            return x => x.UserId == value;
        }
        /// <summary>精确匹配：UXAuthRefreshTokenTokenHash（Unique 索引，必填参数）</summary>
        public static Expression<Func<AuthRefreshTokenEntity, bool>> ByUXAuthRefreshTokenTokenHash(string tokenHash)
            => x => x.TokenHash == tokenHash;

        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<AuthRefreshTokenEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<AuthRefreshTokenEntity, bool>> All(params Expression<Func<AuthRefreshTokenEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<AuthRefreshTokenEntity, bool>> Any(params Expression<Func<AuthRefreshTokenEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>AuthRefreshTokenEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<AuthRefreshTokenEntity>
    {

        /// <summary>组合条件：IXAuthRefreshTokenUserVersion（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXAuthRefreshTokenUserVersion(int tokenVersion, string userId)
            => (PredicateBuilder)Update(Conditions.ByIXAuthRefreshTokenUserVersion(tokenVersion, userId));

        /// <summary>模糊搜索：UserId（单个关键字）</summary>
        public PredicateBuilder LikeUserId(string? userId = null)
            => (PredicateBuilder)Update(Conditions.LikeUserId(userId));

        /// <summary>多值模糊搜索：IXAuthRefreshTokenUserVersion（按关键词 Or-链）</summary>
        public PredicateBuilder LikeIXAuthRefreshTokenUserVersionKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeIXAuthRefreshTokenUserVersionKeywords(keywords));

        /// <summary>跨属性精确匹配：IXAuthRefreshTokenUserVersion（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualIXAuthRefreshTokenUserVersion(string value)
            => (PredicateBuilder)Update(Conditions.EqualIXAuthRefreshTokenUserVersion(value));

        /// <summary>精确匹配：UXAuthRefreshTokenTokenHash（Unique 索引，必填参数）</summary>
        public PredicateBuilder ByUXAuthRefreshTokenTokenHash(string tokenHash)
            => (PredicateBuilder)Update(Conditions.ByUXAuthRefreshTokenTokenHash(tokenHash));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<AuthRefreshTokenEntity> CreateBranch() => new PredicateBuilder();
}
}
