// <auto-generated>
// 此文件由 xCodeGen 自动生成，请勿手动修改。
// @[xCodeGen.Hash: 7b96b2c445b0b3b9d463f674f690f207df1924f486f516c3225c0ebfc6d95d49]
// 模型: AuthLoginAttemptEntity (TKWF.Ext.AuthCenter.AuthLoginAttemptEntity)
// 生成时间: 2026-10-06 05:00:32
// </auto-generated>
#nullable enable
using System;
using System.Linq.Expressions;
using TKW.Framework;
using TKW.Framework.Domain;
using TKW.Framework.Extensions;

namespace TKWF.Ext.AuthCenter;

// V4.10.24 (G10): 实体类级 XML Doc 移入手写实体类（[DomainGenerateCode] partial 声明）——
// 此处不再给 partial class 写 <summary>（旧占位"条件工厂（V4.9）..."会被 Roslyn 合并进
// symbol.GetDocumentationCommentXml()，遮蔽手写实体描述）。条件工厂说明挪至 Conditions 嵌套类上方。
partial class AuthLoginAttemptEntity
{
    // --- 静态条件方法（直接返回 Expression） ---
    /// <summary>
    /// 条件工厂（V4.9）。支持两种使用方式：
    /// <list type="bullet">
    /// <item><c>AuthLoginAttemptEntity.Conditions.ByXxx(value)</c> — 直接返回表达式（已有代码兼容）</item>
    /// <item><c>AuthLoginAttemptEntity.Where.ByXxx(value).ByYyy(value)</c> — 链式组合，隐式转换到 Expression</item>
    /// </list>
    /// </summary>
    public static class Conditions
    {
        /// <summary>组合条件：IXAuthLoginAttemptUserAuthTime（AND 连接，单值必填/范围可选）</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> ByIXAuthLoginAttemptUserAuthTime(string userIdentity, string authType, DateTime? beginAttemptTime = null, DateTime? endAttemptTime = null)
        {
            return x => x.UserIdentity == userIdentity &&
            x.AuthType == authType &&
            (!beginAttemptTime.HasValue || x.AttemptTime >= beginAttemptTime.Value) &&
            (!endAttemptTime.HasValue || x.AttemptTime <= endAttemptTime.Value);
        }

        /// <summary>模糊搜索：UserIdentity（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> LikeUserIdentity(string? userIdentity = null)
        {
            if (string.IsNullOrEmpty(userIdentity)) return None;
            var val = userIdentity!;
            return x => x.UserIdentity.Contains(val);
        }
        /// <summary>模糊搜索：AuthType（单个关键字；为空返回无条件）</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> LikeAuthType(string? authType = null)
        {
            if (string.IsNullOrEmpty(authType)) return None;
            var val = authType!;
            return x => x.AuthType.Contains(val);
        }
        /// <summary>多值模糊搜索：IXAuthLoginAttemptUserAuthTime（按 UserIdentity Or-链）</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> LikeIXAuthLoginAttemptUserAuthTimeKeywords(string[]? keywords = null)
        {
            if (keywords == null || keywords.Length == 0) return None;
            return ConditionsHelper.BuildMultiOrLike<AuthLoginAttemptEntity>(x => x.UserIdentity, keywords) ?? None;
        }
        /// <summary>跨属性模糊搜索：IXAuthLoginAttemptUserAuthTime（单个关键字在多个字符串属性中 OR 匹配）</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> LikeIXAuthLoginAttemptUserAuthTime(string? keyword = null)
        {
            if (string.IsNullOrEmpty(keyword)) return None;
            var kw = keyword!;
            return x => x.UserIdentity.Contains(kw) ||
                x.AuthType.Contains(kw);
        }
        /// <summary>跨属性精确匹配：IXAuthLoginAttemptUserAuthTime（至少一个字符串属性等于 value）</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> EqualIXAuthLoginAttemptUserAuthTime(string value)
        {
            return x => x.UserIdentity == value ||
                x.AuthType == value;
        }
        /// <summary>时间范围：AttemptTime（begin/end 可选，返回非可空）</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> ByAttemptTimeRange(DateTime? begin = null, DateTime? end = null)
        {
            return x => (!begin.HasValue || x.AttemptTime >= begin.Value)
                     && (!end.HasValue || x.AttemptTime <= end.Value);
        }
        /// <summary>恒真表达式（无筛选条件时的 Identity 值）</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> None => x => true;

        /// <summary>组合多个条件（AND 连接）。所有条件同时满足。</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> All(params Expression<Func<AuthLoginAttemptEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.And(result, predicates[i]);
            return result;
        }

        /// <summary>组合多个条件（OR 连接）。任一条件满足即可。</summary>
        public static Expression<Func<AuthLoginAttemptEntity, bool>> Any(params Expression<Func<AuthLoginAttemptEntity, bool>>[] predicates)
        {
            if (predicates == null || predicates.Length == 0) return None;
            var result = predicates[0];
            for (int i = 1; i < predicates.Length; i++)
                result = PredicateExtensions.Or(result, predicates[i]);
            return result;
        }
    }

    // --- 链式 Builder（Entity.Where.ByXxx().ByYyy()，基类 PredicateBuilderBase<T> 提供 Update/Where/Or/If/隐式转换） ---
    /// <summary>链式条件构造器入口。<c>AuthLoginAttemptEntity.Where.ByMemberId(123).ByStatus(1)</c></summary>
    public static PredicateBuilder Where => new PredicateBuilder();

    public sealed class PredicateBuilder : PredicateBuilderBase<AuthLoginAttemptEntity>
    {

        /// <summary>组合条件：IXAuthLoginAttemptUserAuthTime（AND 连接，单值必填/范围可选）</summary>
        public PredicateBuilder ByIXAuthLoginAttemptUserAuthTime(string userIdentity, string authType, DateTime? beginAttemptTime = null, DateTime? endAttemptTime = null)
            => (PredicateBuilder)Update(Conditions.ByIXAuthLoginAttemptUserAuthTime(userIdentity, authType, beginAttemptTime, endAttemptTime));

        /// <summary>模糊搜索：UserIdentity（单个关键字）</summary>
        public PredicateBuilder LikeUserIdentity(string? userIdentity = null)
            => (PredicateBuilder)Update(Conditions.LikeUserIdentity(userIdentity));

        /// <summary>模糊搜索：AuthType（单个关键字）</summary>
        public PredicateBuilder LikeAuthType(string? authType = null)
            => (PredicateBuilder)Update(Conditions.LikeAuthType(authType));

        /// <summary>多值模糊搜索：IXAuthLoginAttemptUserAuthTime（按关键词 Or-链）</summary>
        public PredicateBuilder LikeIXAuthLoginAttemptUserAuthTimeKeywords(string[]? keywords = null)
            => (PredicateBuilder)Update(Conditions.LikeIXAuthLoginAttemptUserAuthTimeKeywords(keywords));

        /// <summary>跨属性模糊搜索：IXAuthLoginAttemptUserAuthTime（单个关键字在多个字符串属性中 OR 匹配）</summary>
        public PredicateBuilder LikeIXAuthLoginAttemptUserAuthTime(string? keyword = null)
            => (PredicateBuilder)Update(Conditions.LikeIXAuthLoginAttemptUserAuthTime(keyword));

        /// <summary>跨属性精确匹配：IXAuthLoginAttemptUserAuthTime（至少一个字符串属性等于 value）</summary>
        public PredicateBuilder EqualIXAuthLoginAttemptUserAuthTime(string value)
            => (PredicateBuilder)Update(Conditions.EqualIXAuthLoginAttemptUserAuthTime(value));

        /// <summary>时间范围：AttemptTime（begin/end 可选）</summary>
        public PredicateBuilder ByAttemptTimeRange(DateTime? begin = null, DateTime? end = null)
            => (PredicateBuilder)Update(Conditions.ByAttemptTimeRange(begin, end));
        // V4.9: 工厂方法（AOT 兼容，替代 Activator.CreateInstance）
        protected override PredicateBuilderBase<AuthLoginAttemptEntity> CreateBranch() => new PredicateBuilder();
}
}
