// <auto-generated>
// 手动创建（对齐 xCodeGen 生成格式）
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Entity;
using TKWF.Ext.Approval;
using TKWF.Ext.Approval.DTOs;
using TKW.Framework.Domain.Interfaces;
using System.ComponentModel;

namespace TKWF.Ext.Approval;

sealed partial class ApprovalTaskEntityDataService : IGeneratedByxCodeGenCli
{
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal IQueryable<ApprovalTaskEntity> Query => QueryForUser();

    internal Task<ApprovalTaskEntity?> EntityGetAsync(Expression<Func<ApprovalTaskEntity, bool>> predicate, CancellationToken ct = default)
        => InternalGetAsync(predicate, ct);

    internal Task<List<ApprovalTaskEntity>> EntitySelectAsync(
        Expression<Func<ApprovalTaskEntity, bool>>? predicate,
        int skip = 0, int limit = 100,
        Func<IQueryable<ApprovalTaskEntity>, IQueryable<ApprovalTaskEntity>>? orderBy = null,
        CancellationToken ct = default)
        => InternalSelectAsync(predicate, skip, limit, orderBy, ct);

    internal Task<ApprovalTaskEntity> EntityCreateAsync(ApprovalTaskEntity entity, CancellationToken ct = default)
        => InternalCreateAsync(entity, ct);

    internal Task<ApprovalTaskEntity> EntityUpdateAsync(ApprovalTaskEntity entity, CancellationToken ct = default)
        => InternalUpdateAsync(entity, ct);

    internal Task<List<ApprovalTaskEntity>> EntityCreateBatchAsync(IEnumerable<ApprovalTaskEntity> entities, CancellationToken ct = default)
        => InternalCreateBatchAsync(entities, ct);

    internal Task EntityUpdateBatchAsync(IEnumerable<ApprovalTaskEntity> entities, CancellationToken ct = default)
        => InternalUpdateBatchAsync(entities, ct);

    internal Task<int> EntityUpdateColumnsBatchAsync<TColumns>(
        IEnumerable<ApprovalTaskEntity> entities,
        Expression<Func<ApprovalTaskEntity, TColumns>> columns,
        CancellationToken ct = default)
        => InternalUpdateColumnsBatchAsync(entities, columns, ct);

    internal Task<bool> EntitySoftDeleteAsync(long id, CancellationToken ct = default)
        => InternalSoftDeleteAsync(id, ct);
}
