// <auto-generated>
// 手动创建（对齐 xCodeGen 生成格式）
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Entity;
using TKWF.Ext.Approval;
using TKWF.Ext.Approval.DTOs;
using TKW.Framework.Domain.Interfaces;
using System.ComponentModel;

namespace TKWF.Ext.Approval;

sealed partial class ApprovalCCEntityDataService : IGeneratedByxCodeGenCli
{
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal IQueryable<ApprovalCCEntity> Query => QueryForUser();

    internal Task<ApprovalCCEntity?> EntityGetAsync(Expression<Func<ApprovalCCEntity, bool>> predicate, CancellationToken ct = default)
        => InternalGetAsync(predicate, ct);

    internal Task<List<ApprovalCCEntity>> EntitySelectAsync(
        Expression<Func<ApprovalCCEntity, bool>>? predicate,
        int skip = 0, int limit = 100,
        Func<IQueryable<ApprovalCCEntity>, IQueryable<ApprovalCCEntity>>? orderBy = null,
        CancellationToken ct = default)
        => InternalSelectAsync(predicate, skip, limit, orderBy, ct);

    internal Task<ApprovalCCEntity> EntityCreateAsync(ApprovalCCEntity entity, CancellationToken ct = default)
        => InternalCreateAsync(entity, ct);

    internal Task<ApprovalCCEntity> EntityUpdateAsync(ApprovalCCEntity entity, CancellationToken ct = default)
        => InternalUpdateAsync(entity, ct);

    internal Task<List<ApprovalCCEntity>> EntityCreateBatchAsync(IEnumerable<ApprovalCCEntity> entities, CancellationToken ct = default)
        => InternalCreateBatchAsync(entities, ct);

    internal Task EntityUpdateBatchAsync(IEnumerable<ApprovalCCEntity> entities, CancellationToken ct = default)
        => InternalUpdateBatchAsync(entities, ct);

    internal Task<int> EntityUpdateColumnsBatchAsync<TColumns>(
        IEnumerable<ApprovalCCEntity> entities,
        Expression<Func<ApprovalCCEntity, TColumns>> columns,
        CancellationToken ct = default)
        => InternalUpdateColumnsBatchAsync(entities, columns, ct);

    internal Task<bool> EntitySoftDeleteAsync(long id, CancellationToken ct = default)
        => InternalSoftDeleteAsync(id, ct);
}
