// <auto-generated>
// 手动创建（对齐 xCodeGen 生成格式）
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using TKW.Framework.CodeGeneration;
using TKW.Framework.Domain;
using TKW.Framework.Entity;
using TKWF.Ext.Approval;
using TKWF.Ext.Approval.DTOs;
using TKW.Framework.Domain.Interfaces;
using System.ComponentModel;

namespace TKWF.Ext.Approval;

sealed partial class ApprovalFlowEntityDataService : IGeneratedByxCodeGenCli
{
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal IQueryable<ApprovalFlowEntity> Query => QueryForUser();

    internal Task<ApprovalFlowEntity?> EntityGetAsync(Expression<Func<ApprovalFlowEntity, bool>> predicate, CancellationToken ct = default)
        => InternalGetAsync(predicate, ct);

    internal Task<List<ApprovalFlowEntity>> EntitySelectAsync(
        Expression<Func<ApprovalFlowEntity, bool>>? predicate,
        int skip = 0, int limit = 100,
        Func<IQueryable<ApprovalFlowEntity>, IQueryable<ApprovalFlowEntity>>? orderBy = null,
        CancellationToken ct = default)
        => InternalSelectAsync(predicate, skip, limit, orderBy, ct);

    internal Task<ApprovalFlowEntity> EntityCreateAsync(ApprovalFlowEntity entity, CancellationToken ct = default)
        => InternalCreateAsync(entity, ct);

    internal Task<ApprovalFlowEntity> EntityUpdateAsync(ApprovalFlowEntity entity, CancellationToken ct = default)
        => InternalUpdateAsync(entity, ct);

    internal Task<bool> EntitySoftDeleteAsync(long id, CancellationToken ct = default)
        => InternalSoftDeleteAsync(id, ct);
}
